/**
 * The prompts themselves. One row per prompt:
 *
 *   [category, text, specific, open, charge, doable, grounded, flags]
 *
 * The five numbers are the rubric in src/lib/prompt-bank.ts, each 1 to 5.
 * Flags are letters: `p` lands on somebody's actual life (a household, money,
 * a body, a death), `a` needs adult knowledge (a job, a tenancy, a marriage),
 * `l` has a built-in performer role. A school room gets none of the three; a
 * work room gets `a` back. Three more since 2026-09-30: `x` does not read as
 * one line of a who-where-what draw (a relationship that names its place, a
 * task that names its people, a constraint), `g` needs three or more, `d` is
 * a pair worth saying so on the card. A ninth element is one coaching line
 * for the room, on the strongest prompts only. Everything the article lists is here, in the order
 * the article lists it, followed by the rest.
 *
 * Scoring is judgement, applied consistently rather than perfectly. The
 * question for each axis is written next to it in prompt-bank.ts. If a prompt
 * feels misplaced when it comes up, the fix is a number here, not a rewrite of
 * the ranking.
 */

import type { PromptCategory } from "./prompt-bank";

type PromptRow = [
  category: PromptCategory,
  text: string,
  specific: number,
  open: number,
  charge: number,
  doable: number,
  grounded: number,
  flags?: string,
  coach?: string,
];

// prettier-ignore
export const PROMPT_ROWS: PromptRow[] = [
  // ── Relationships ────────────────────────────────────────────────────────
  ["relationship", "Two siblings clearing out their mother's house", 5, 4, 5, 4, 5, "px", "Fight about the objects, never about her."],
  ["relationship", "A driving instructor and a student who is forty", 4, 4, 3, 4, 5, "a"],
  ["relationship", "Best friends, one of whom just got the job the other applied for", 4, 4, 5, 3, 5, "a"],
  ["relationship", "A couple on the drive home from a party", 4, 5, 4, 4, 5, "ax"],
  ["relationship", "Two people who used to be in a band together", 4, 5, 4, 3, 5],
  ["relationship", "A doctor and a patient who went to school together", 4, 4, 4, 3, 5, "a"],
  ["relationship", "Neighbours who share a fence and disagree about it", 4, 4, 4, 4, 5, "a"],
  ["relationship", "A parent helping an adult child move out again", 5, 4, 5, 4, 5, "p"],
  ["relationship", "Two people who matched online and have now met", 4, 4, 4, 4, 5, "a"],
  ["relationship", "A manager and the person they are about to promote", 3, 4, 4, 3, 5, "a"],
  ["relationship", "Old friends, one of whom has become religious", 4, 4, 4, 3, 5, "p"],
  ["relationship", "A landlord and a tenant who is three weeks late", 4, 3, 5, 4, 5, "pa"],
  ["relationship", "Two colleagues stuck between floors", 4, 5, 3, 4, 5, "ax"],
  ["relationship", "A grandparent teaching a grandchild to drive", 5, 4, 4, 4, 5, "p", "Stay in the car. The lesson is the excuse for everything else."],
  ["relationship", "Someone and their ex's new partner", 4, 4, 5, 3, 5, "p"],
  ["relationship", "Two people who were briefly famous together", 4, 5, 4, 2, 4],
  ["relationship", "A coach and the player they are dropping", 4, 3, 5, 4, 5],
  ["relationship", "Roommates dividing what they bought together", 4, 4, 4, 5, 5, "a"],
  ["relationship", "A translator and the person they are translating for", 4, 5, 3, 4, 5],
  ["relationship", "Someone visiting a friend in hospital", 5, 4, 5, 4, 5, "px"],
  ["relationship", "Two people who have been on one date before", 4, 4, 4, 4, 5, "a"],
  ["relationship", "A parent and the teacher who called them in", 4, 4, 5, 4, 5, "p"],
  ["relationship", "Siblings deciding who takes the dog", 4, 4, 5, 4, 5, "p"],
  ["relationship", "A priest and someone who has stopped coming", 4, 4, 5, 3, 5, "p"],
  ["relationship", "Two people who used to work night shifts together", 4, 5, 3, 3, 5, "a"],
  ["relationship", "A tailor and a customer for a suit they will wear once", 5, 4, 4, 5, 5, "", "Let the fitting be the scene; what the suit is for arrives on its own."],
  ["relationship", "Someone and the person who trained them, years later", 4, 5, 4, 3, 5, "a"],
  ["relationship", "Two people who survived the same accident", 4, 4, 5, 2, 4, "p"],
  ["relationship", "A new kid and the one told to show them round", 4, 4, 3, 5, 5],
  ["relationship", "Two people paired for a project who have never spoken", 4, 5, 3, 5, 5],
  ["relationship", "A street musician and the one person who stopped", 5, 4, 3, 4, 5, "x"],
  ["relationship", "A lifeguard and a swimmer who will not get out", 4, 4, 3, 5, 5],
  ["relationship", "Two strangers at a bus stop, one of whom has an umbrella", 4, 5, 2, 5, 5, "x"],
  ["relationship", "A librarian and someone returning a book ten years late", 5, 4, 3, 5, 5],
  ["relationship", "Two pen pals meeting for the first time", 4, 4, 4, 4, 5],
  ["relationship", "Team captains picking sides who both want the same person", 4, 4, 4, 5, 5, "gx"],
  ["relationship", "A shop assistant and a customer returning a gift without a receipt", 4, 4, 3, 5, 5],
  ["relationship", "A referee and the player they have just sent off", 4, 3, 4, 5, 5],
  ["relationship", "Two people who camped out overnight for tickets and ended up next to each other", 4, 5, 2, 4, 5, "x"],
  ["relationship", "A dog walker and the owner of the dog", 4, 4, 3, 4, 5],
  ["relationship", "Two people who are both early for the same interview", 4, 4, 4, 4, 5, "ax"],
  ["relationship", "The last two people at a party", 4, 5, 3, 4, 5, "ax"],
  ["relationship", "A mentor and the mentee who has overtaken them", 4, 4, 5, 3, 5, "a"],
  ["relationship", "Two people who share a birthday and a name", 3, 5, 2, 3, 4],
  ["relationship", "A piano teacher and a pupil who has not practised", 5, 4, 3, 5, 5],
  ["relationship", "Two neighbours who only ever meet on recycling day", 4, 5, 2, 5, 5, "a"],
  ["relationship", "A bride's parents meeting the groom's, the night before", 4, 4, 4, 3, 5, "px"],
  ["relationship", "Two old friends who have not spoken since the argument", 3, 5, 5, 3, 5],
  ["relationship", "A babysitter and the parent who has come home early", 4, 4, 4, 4, 5, "px"],
  ["relationship", "Two people who were both promised the window seat", 4, 4, 3, 5, 5],
  ["relationship", "A ghostwriter and the person whose name will be on the book", 4, 4, 4, 3, 5, "a"],
  ["relationship", "The understudy and the lead, ten minutes before curtain", 5, 4, 5, 4, 5, "x", "Both want the same thing and neither can say it; keep the clock running."],
  ["relationship", "Two people on a tandem who disagree about the route", 5, 4, 3, 5, 5, "x"],
  ["relationship", "A retiring postal worker and someone on the last house of the round", 5, 4, 4, 4, 5, "a"],
  ["relationship", "Two waiters splitting the tips on a bad night", 4, 4, 4, 5, 5, "ax"],
  ["relationship", "A hairdresser and a regular who wants something different this time", 5, 4, 4, 5, 5],
  ["relationship", "A sponsor and the runner they are waiting for at the finish", 4, 4, 4, 4, 5, "x"],
  ["relationship", "Two people who have been put in the same tent", 4, 5, 3, 5, 5, "x"],
  ["relationship", "Someone and the person who found their wallet", 4, 4, 3, 5, 5],
  ["relationship", "The person who locks the school at night and a student who is still inside", 5, 4, 3, 5, 5, "x"],
  ["relationship", "A stage manager and an actor who keeps missing the cue", 4, 4, 4, 5, 5, "x"],
  ["relationship", "Two people at a reunion, both pretending to remember each other", 4, 5, 4, 4, 5, "x"],
  ["relationship", "Someone renting a room and the family whose house it is, at breakfast", 4, 4, 3, 4, 5, "ax"],
  ["relationship", "Two people carrying opposite ends of the same sofa up a stair", 5, 4, 3, 5, 5, "x"],
  ["relationship", "A window cleaner and someone who has just woken up", 5, 5, 3, 5, 5, "x"],
  ["relationship", "Two people who are both sure the seat is theirs", 4, 4, 3, 5, 5],
  ["relationship", "A plumber and a customer who has already tried to fix it", 5, 4, 3, 5, 5, "a"],
  ["relationship", "A student and the teacher who wrote their reference", 4, 4, 4, 3, 5],
  ["relationship", "Two cousins who only meet at weddings", 4, 5, 3, 3, 5, "p"],
  ["relationship", "A shopkeeper and a child with the wrong change", 4, 4, 3, 5, 5],
  ["relationship", "A guide and the one tourist who keeps wandering off", 4, 4, 3, 5, 5],
  ["relationship", "Two people waiting at arrivals for the same person", 5, 4, 4, 4, 5, "x"],
  ["relationship", "The retiring head of a school and the student they expelled", 4, 4, 5, 3, 5, "a"],
  ["relationship", "A florist and someone ordering flowers for an apology", 5, 4, 4, 5, 5],
  ["relationship", "Two people who have just swapped shifts and regret it", 4, 4, 3, 4, 5, "a"],
  ["relationship", "A trainee and the customer who knows more than they do", 4, 4, 3, 5, 5, "a"],
  ["relationship", "Two people who have each been told the other is in charge", 3, 5, 4, 5, 5],
  ["relationship", "The person who won the raffle and the person who ran it", 4, 4, 3, 5, 5],
  ["relationship", "Someone and the friend who cut their hair for the first time", 5, 4, 4, 5, 5],
  ["relationship", "Two housemates, one of whom has adopted a cat without asking", 5, 4, 4, 5, 5, "a"],
  ["relationship", "A junior doctor and a senior nurse at the end of a long night", 4, 4, 4, 3, 5, "ax"],
  ["relationship", "Two hikers who have taken the wrong path", 4, 4, 3, 5, 5, "x"],
  ["relationship", "A ticket inspector and someone with the wrong ticket", 4, 4, 4, 5, 5],
  ["relationship", "A best man and the groom, an hour before", 5, 4, 5, 4, 5, "ax"],
  ["relationship", "Someone and the neighbour who has been keeping their parcel", 4, 4, 3, 5, 5, "a"],
  ["relationship", "A choir director and the singer who is always flat", 4, 4, 4, 5, 5],
  ["relationship", "Two people who both got engaged the same weekend", 4, 4, 4, 3, 5, "a"],
  ["relationship", "The oldest and the youngest at a family reunion", 4, 5, 3, 3, 5, "px"],
  ["relationship", "A long-haul driver and a hitchhiker in the second hour", 5, 5, 3, 3, 5, "ax"],
  ["relationship", "A gardener and the person whose garden it is", 4, 4, 3, 5, 5],
  ["relationship", "Two people who both volunteered for the job nobody wanted", 4, 5, 4, 4, 5],
  ["relationship", "Someone renting a room and the owner of the house, who can smell the cooking", 4, 4, 3, 4, 5, "a"],
  ["relationship", "Two players who have been substituted at the same time", 4, 4, 4, 4, 5, "x"],
  ["relationship", "An apprentice and the master who is about to retire", 4, 4, 4, 4, 5, "a"],

  // ── First lines ──────────────────────────────────────────────────────────
  ["first-line", "She has your eyes.", 5, 5, 5, 5, 5, "", "Whoever hears it decides who she is. Do not explain; answer."],
  ["first-line", "You said you'd stopped.", 4, 5, 5, 5, 5],
  ["first-line", "Everyone's outside. They're waiting for you.", 4, 5, 4, 5, 5],
  ["first-line", "I found the receipts.", 4, 4, 5, 5, 5, "p"],
  ["first-line", "Don't tell your mother I let you do this.", 5, 5, 4, 5, 5, "p"],
  ["first-line", "This is the last time I'm asking.", 3, 5, 5, 5, 5],
  ["first-line", "It doesn't look like the photo.", 4, 5, 3, 5, 5],
  ["first-line", "I've been standing here for an hour.", 4, 5, 4, 5, 5],
  ["first-line", "You're the only one who wrote back.", 4, 5, 5, 5, 5],
  ["first-line", "Whose car is that?", 4, 5, 4, 5, 5],
  ["first-line", "I brought the thing you asked for.", 4, 5, 3, 5, 5],
  ["first-line", "Nobody's used this room since.", 5, 5, 4, 5, 5],
  ["first-line", "I'm going to need you to sit down.", 4, 5, 5, 5, 5],
  ["first-line", "You always sit on my side.", 4, 4, 4, 5, 5],
  ["first-line", "They said you'd know what to do.", 4, 5, 4, 5, 5],
  ["first-line", "It was cheaper than the alternative.", 4, 5, 3, 5, 5],
  ["first-line", "You've done something to your hair.", 5, 5, 3, 5, 5],
  ["first-line", "I'm not signing that.", 4, 4, 5, 5, 5, "a"],
  ["first-line", "Third time this month.", 4, 5, 4, 5, 5],
  ["first-line", "I kept your chair.", 5, 5, 5, 5, 5, "", "Sit down or refuse to. The scene is in which."],
  ["first-line", "Your father would have hated this.", 5, 4, 5, 5, 5, "p"],
  ["first-line", "Put it back exactly where it was.", 4, 5, 4, 5, 5],
  ["first-line", "I told them you were coming.", 4, 5, 4, 5, 5],
  ["first-line", "We agreed we wouldn't talk about it.", 3, 5, 5, 5, 5],
  ["first-line", "You're early. Nobody's ever early.", 4, 5, 3, 5, 5],
  ["first-line", "I didn't know you still had that.", 4, 5, 4, 5, 5],
  ["first-line", "Is that the same coat?", 4, 5, 3, 5, 5],
  ["first-line", "I've told the others you're not coming.", 4, 5, 4, 5, 5],
  ["first-line", "Sit anywhere except there.", 4, 5, 3, 5, 5],
  ["first-line", "The key was under the wrong pot.", 5, 5, 3, 5, 5],
  ["first-line", "I made too much, so.", 4, 5, 3, 5, 5],
  ["first-line", "Say that again, slower.", 3, 5, 4, 5, 5],
  ["first-line", "They've changed the locks.", 4, 5, 4, 5, 5],
  ["first-line", "I've got about four minutes.", 4, 5, 4, 5, 5],
  ["first-line", "You were supposed to bring the chairs.", 4, 4, 3, 5, 5],
  ["first-line", "Nobody told me it was a costume party.", 5, 4, 3, 5, 5],
  ["first-line", "I saw the light on.", 4, 5, 4, 5, 5],
  ["first-line", "It's not as bad as it looks.", 3, 5, 4, 5, 5],
  ["first-line", "We're going to have to walk.", 4, 5, 3, 5, 5],
  ["first-line", "I've never told anyone this.", 3, 5, 5, 5, 5],
  ["first-line", "You still owe me for the taxi.", 4, 4, 3, 5, 5, "p"],
  ["first-line", "The bus isn't coming.", 4, 5, 3, 5, 5],
  ["first-line", "I've named him after you.", 5, 5, 5, 5, 5, "", "The second line is a question, and the answer is the scene."],
  ["first-line", "Please don't make a thing of it.", 3, 5, 4, 5, 5],
  ["first-line", "I read the letter.", 4, 5, 5, 5, 5],
  ["first-line", "Everyone's gone home.", 4, 5, 3, 5, 5],
  ["first-line", "I'll do the talking.", 3, 5, 4, 5, 5],
  ["first-line", "You've been in my room.", 4, 5, 4, 5, 5],
  ["first-line", "It was a lot smaller in the picture.", 4, 5, 3, 5, 5],
  ["first-line", "I know it's late.", 3, 5, 4, 5, 5],
  ["first-line", "There's someone in your seat.", 4, 5, 3, 5, 5],
  ["first-line", "This isn't the way home.", 4, 5, 4, 5, 5],
  ["first-line", "I've had this since I was nine.", 5, 5, 4, 5, 5],
  ["first-line", "Nobody's supposed to be down here.", 4, 5, 4, 5, 5],
  ["first-line", "I've done something to the car.", 4, 5, 4, 5, 5],
  ["first-line", "Take your shoes off first.", 4, 5, 2, 5, 5],
  ["first-line", "I got you the wrong size.", 4, 5, 3, 5, 5],
  ["first-line", "They asked me to talk to you.", 3, 5, 5, 5, 5],
  ["first-line", "I was here first.", 3, 5, 3, 5, 5],
  ["first-line", "It's the last one, so we share.", 4, 5, 3, 5, 5],
  ["first-line", "You're standing on it.", 4, 5, 2, 5, 5],
  ["first-line", "I've kept every one.", 4, 5, 5, 5, 5],
  ["first-line", "Don't look at the ceiling.", 5, 5, 3, 5, 5],
  ["first-line", "We used to come here.", 4, 5, 4, 5, 5],
  ["first-line", "I can't find the dog.", 5, 5, 4, 5, 5],
  ["first-line", "You've got until the kettle boils.", 5, 5, 4, 5, 5],
  ["first-line", "I'm not wearing that.", 4, 5, 3, 5, 5],
  ["first-line", "It's not mine, before you ask.", 4, 5, 4, 5, 5],
  ["first-line", "She left this for you.", 4, 5, 5, 5, 5],
  ["first-line", "I counted, and there are only eleven.", 5, 5, 3, 5, 5],
  ["first-line", "You'll want to sit for this.", 3, 5, 5, 5, 5],
  ["first-line", "I've been practising that all week.", 4, 5, 3, 5, 5],
  ["first-line", "The tide's coming in.", 5, 5, 4, 5, 5],
  ["first-line", "I didn't recognise you without the hat.", 5, 5, 3, 5, 5],
  ["first-line", "We've got the wrong house.", 4, 5, 4, 5, 5],
  ["first-line", "Why is there a ladder against the window?", 5, 5, 3, 5, 5],
  ["first-line", "I've got your bag. You've got mine.", 5, 4, 3, 5, 5],
  ["first-line", "It's fine. I've already eaten.", 4, 5, 4, 5, 5],
  ["first-line", "Whatever you do, don't open the box.", 4, 4, 3, 5, 4],

  // ── Locations ────────────────────────────────────────────────────────────
  ["location", "A laundromat at two in the morning", 5, 5, 3, 5, 5, "", "Nobody is here at two by choice. Play the reason without naming it."],
  ["location", "The waiting area at a passport office", 4, 5, 3, 5, 5],
  ["location", "A rented camper in the rain", 5, 5, 3, 5, 5],
  ["location", "Backstage at a school play", 5, 5, 4, 5, 5, "x", "Voices down, stakes up. The show is going on out there."],
  ["location", "A flea market, packing up", 5, 5, 3, 5, 5],
  ["location", "The waiting room of a fertility clinic", 5, 4, 5, 4, 5, "p"],
  ["location", "A hotel breakfast buffet", 5, 5, 2, 5, 5],
  ["location", "An empty office on Christmas Eve", 5, 5, 4, 4, 5, "a"],
  ["location", "A cable car that has stopped", 5, 4, 4, 4, 5],
  ["location", "The corner of the plant nursery nobody goes to", 5, 5, 3, 5, 5],
  ["location", "A funeral director's showroom", 5, 4, 5, 4, 5, "p"],
  ["location", "A laundromat that is also a post office", 5, 5, 2, 5, 5],
  ["location", "The car park after the wedding", 5, 5, 4, 4, 5, "a"],
  ["location", "A campsite where it will not stop raining", 5, 5, 3, 5, 5],
  ["location", "Someone's childhood bedroom, unchanged", 5, 5, 5, 5, 5, "p", "Touch three things before anyone says why you are here."],
  ["location", "A ferry crossing in bad weather", 5, 5, 3, 5, 5],
  ["location", "The lost property room at a station", 5, 5, 3, 5, 5],
  ["location", "A shed at the bottom of a garden", 5, 5, 3, 5, 5],
  ["location", "An airport gate after the last flight", 5, 5, 4, 4, 5],
  ["location", "A lighthouse, being decommissioned", 5, 4, 4, 3, 5],
  ["location", "A school corridor during an exam", 5, 5, 3, 5, 5],
  ["location", "The back row of a coach on a long trip", 5, 5, 3, 5, 5],
  ["location", "A swimming pool changing room, after closing", 5, 5, 3, 5, 5],
  ["location", "A phone box that still works", 5, 5, 3, 4, 5],
  ["location", "The last checkout open at a supermarket", 5, 5, 3, 5, 5],
  ["location", "A community hall being set up for something", 5, 5, 2, 5, 5],
  ["location", "The top deck of a bus in the rain", 5, 5, 3, 5, 5],
  ["location", "A stairwell in a multi-storey car park", 5, 5, 3, 5, 5],
  ["location", "The kitchen at a wedding reception", 5, 5, 3, 5, 5],
  ["location", "A community garden plot in November", 5, 5, 3, 5, 5],
  ["location", "A dentist's waiting room with the radio on", 5, 5, 3, 5, 5],
  ["location", "An elevator that has stopped between floors", 4, 4, 4, 4, 5],
  ["location", "A bookshop five minutes before closing", 5, 5, 3, 5, 5],
  ["location", "The changing rooms at a clothes shop", 5, 5, 3, 5, 5],
  ["location", "A pier in the off-season", 5, 5, 3, 5, 5],
  ["location", "A canal path at dusk", 5, 5, 3, 4, 5],
  ["location", "The waiting area at a tyre garage", 5, 5, 2, 5, 5],
  ["location", "The staff room during a fire drill", 5, 5, 3, 5, 5],
  ["location", "A museum gift shop", 5, 5, 2, 5, 5],
  ["location", "A rooftop with washing lines", 5, 5, 3, 5, 5],
  ["location", "A tent in a back garden", 5, 5, 3, 5, 5],
  ["location", "The kiosk at an ice rink", 5, 5, 2, 5, 5],
  ["location", "A night bus, the last one", 5, 5, 4, 5, 5],
  ["location", "A hospital corridor at visiting time", 5, 4, 4, 4, 5, "p"],
  ["location", "A vet's waiting room", 5, 5, 4, 5, 5],
  ["location", "A car wash, from inside the car", 5, 5, 3, 5, 5],
  ["location", "A school library in the summer holidays", 5, 5, 3, 5, 5],
  ["location", "The changing hut on a beach", 5, 5, 3, 5, 5],
  ["location", "A highway service station at three in the morning", 5, 5, 3, 5, 5],
  ["location", "The self-checkout that keeps needing assistance", 5, 4, 3, 5, 5],
  ["location", "A greenhouse in a heatwave", 5, 5, 3, 5, 5],
  ["location", "The lobby of a hotel that has lost the booking", 5, 4, 4, 5, 5, "a"],
  ["location", "The back room of a second-hand shop, sorting donations", 5, 5, 3, 5, 5],
  ["location", "A bike shed in the rain", 5, 5, 3, 5, 5],
  ["location", "A fire station open day", 5, 5, 2, 5, 5],
  ["location", "A quiz night, between rounds", 5, 5, 3, 5, 5, "ax"],
  ["location", "A hospice garden", 5, 4, 5, 3, 5, "p"],
  ["location", "A crowded elevator with one person holding the door", 5, 5, 3, 5, 5, "x"],
  ["location", "A campground office", 5, 5, 2, 5, 5],
  ["location", "A ballet class, the parents' bench", 5, 5, 3, 4, 5, "px"],
  ["location", "A train yard at the end of the line", 5, 5, 3, 4, 5],
  ["location", "A radio station at four in the morning", 5, 5, 3, 4, 5, "a"],
  ["location", "A barber's, the seat by the window", 5, 5, 3, 5, 5],
  ["location", "The stockroom of a shoe shop", 5, 5, 3, 5, 5],
  ["location", "An aquarium after the school parties have left", 5, 5, 3, 5, 5],
  ["location", "The wait for a photo booth", 5, 5, 3, 5, 5],
  ["location", "A recording booth that smells of the last person", 5, 5, 3, 4, 5],
  ["location", "The tunnel at a stadium before kick-off", 5, 5, 4, 4, 5, "x"],
  ["location", "A model village", 5, 5, 2, 5, 5],
  ["location", "A fish market at dawn", 5, 5, 2, 4, 5],

  // ── Situations ───────────────────────────────────────────────────────────
  ["situation", "Someone has brought the wrong ashes", 5, 4, 5, 4, 4, "p"],
  ["situation", "The cake says the wrong name", 5, 5, 4, 5, 5, "", "Nobody blames the baker. The argument is whose name it should have been."],
  ["situation", "One of you has already spent the money", 4, 4, 5, 4, 5, "p"],
  ["situation", "The house sale falls through on the doorstep", 5, 4, 5, 4, 5, "pa"],
  ["situation", "A gift is being returned to the person who gave it", 4, 5, 5, 5, 5],
  ["situation", "The dog has been to the vet and only one of you knows why", 5, 4, 5, 4, 5],
  ["situation", "Someone has been coming to this class for a year under a false name", 4, 4, 4, 3, 4],
  ["situation", "The recording was left running", 4, 5, 5, 4, 5, "", "Decide silently what is on it, and never play it back."],
  ["situation", "Two people have been sent the same apology letter", 4, 4, 5, 4, 5],
  ["situation", "The inheritance is a boat", 5, 4, 4, 3, 5, "p"],
  ["situation", "Somebody sold the piano", 5, 5, 5, 4, 5, "p", "Play the people who loved it, not the one who sold it."],
  ["situation", "The photograph has someone in it who should not be", 4, 5, 5, 4, 5],
  ["situation", "A speech has to be given and the notes are gone", 5, 4, 4, 5, 5],
  ["situation", "One of you has been fired and has not said", 4, 4, 5, 3, 5, "pa"],
  ["situation", "The neighbours have built something over the line", 4, 4, 4, 4, 5, "a"],
  ["situation", "The ring is the wrong size and it is too late", 5, 4, 5, 4, 5, "a"],
  ["situation", "The wrong suitcase came off the carousel", 5, 5, 3, 5, 5],
  ["situation", "The trophy has already been engraved with the other name", 5, 4, 4, 5, 5],
  ["situation", "The tickets are for yesterday", 5, 4, 4, 5, 5],
  ["situation", "Both of you brought the dessert", 4, 5, 2, 5, 5],
  ["situation", "The instructions are in a language neither of you reads", 4, 5, 2, 5, 5],
  ["situation", "The elevator has stopped and one of you is claustrophobic", 4, 4, 4, 4, 5],
  ["situation", "The costume has arrived in the wrong size an hour before the show", 5, 4, 4, 5, 5],
  ["situation", "One of you has brought the wrong child home from the party", 5, 3, 5, 4, 4, "p"],
  ["situation", "The photo on the passport is not you", 4, 4, 4, 5, 5],
  ["situation", "The map is upside down and you have been walking for an hour", 4, 5, 3, 5, 5],
  ["situation", "The birthday has been forgotten by everyone except one person", 4, 5, 5, 4, 5],
  ["situation", "The last train has gone", 4, 5, 3, 5, 5],
  ["situation", "Someone has painted the room the wrong colour", 5, 5, 3, 5, 5],
  ["situation", "The cat has come back after a year", 5, 5, 4, 4, 5],
  ["situation", "The order has come and it is somebody else's", 4, 5, 2, 5, 5],
  ["situation", "Both of you were told you could have the day off", 4, 5, 3, 5, 5, "a"],
  ["situation", "The plant you were looking after is beyond saving", 5, 5, 4, 5, 5],
  ["situation", "One of you has just seen the other's name on the list", 3, 5, 5, 4, 5],
  ["situation", "The parcel has been opened by the wrong person", 4, 5, 4, 5, 5],
  ["situation", "The seating plan has put you next to each other again", 4, 5, 4, 4, 5],
  ["situation", "The dog has eaten the thing that mattered", 4, 5, 4, 5, 5],
  ["situation", "The kettle is the only thing left in the apartment", 5, 5, 4, 5, 5, "a"],
  ["situation", "Somebody has taken the last chair", 4, 5, 3, 5, 5],
  ["situation", "One of you has already read the ending", 4, 5, 3, 5, 5],
  ["situation", "The song has come on that neither of you can hear without stopping", 4, 5, 5, 4, 5],
  ["situation", "The key is on the inside", 4, 5, 3, 5, 5],
  ["situation", "The bus driver knows you", 4, 5, 3, 5, 5],
  ["situation", "The email went to everyone", 4, 5, 5, 4, 5, "a"],
  ["situation", "The wrong person has been thanked in the speech", 5, 4, 5, 5, 5],
  ["situation", "The tent has one pole missing", 5, 5, 3, 5, 5],
  ["situation", "The photograph in the frame has been swapped", 4, 5, 4, 5, 5],
  ["situation", "The shop has sold the thing that was on hold", 4, 5, 4, 5, 5],
  ["situation", "The trophy cabinet has been cleared", 5, 5, 4, 4, 5],
  ["situation", "The wedding is in an hour and the car will not start", 5, 4, 4, 5, 5, "a"],
  ["situation", "The score was written down wrong", 4, 5, 4, 5, 5],
  ["situation", "The friend you invited has brought someone", 4, 5, 4, 4, 5],
  ["situation", "The rehearsal room has been double-booked", 5, 5, 3, 5, 5],
  ["situation", "The batteries are in the wrong thing", 5, 5, 2, 5, 5],
  ["situation", "Someone has moved the furniture back", 4, 5, 4, 5, 5],
  ["situation", "The results are in the wrong envelope", 4, 4, 4, 5, 5],
  ["situation", "The gift was clearly regifted", 4, 5, 4, 5, 5],
  ["situation", "Everyone has turned up in the same shirt", 5, 4, 2, 5, 5, "g"],
  ["situation", "One of you has been getting the other's post for months", 4, 5, 4, 5, 5],
  ["situation", "The cake has been dropped on the way in", 5, 5, 3, 5, 5],
  ["situation", "The lights have gone out halfway through", 4, 5, 3, 5, 5],
  ["situation", "The bill has been paid by somebody else", 4, 5, 4, 5, 5, "p"],
  ["situation", "The password has been changed and only one of you knows it", 4, 5, 4, 5, 5],
  ["situation", "The audition was yesterday", 5, 4, 5, 5, 5],
  ["situation", "Someone has finally answered the advert", 4, 5, 4, 4, 5],
  ["situation", "The hamster is missing and the class is arriving", 5, 5, 3, 5, 5],
  ["situation", "The wrong film has started", 4, 5, 2, 5, 5],
  ["situation", "The tide has cut you off", 5, 4, 4, 5, 5],

  // ── Questions to ask an audience ─────────────────────────────────────────
  ["audience-question", "What did you do on your last day off?", 4, 5, 3, 5, 5],
  ["audience-question", "What's something you've kept that you should have thrown away?", 5, 5, 4, 5, 5, "", "Put it in the room, in view, and make it the last thing mentioned."],
  ["audience-question", "What is a job you would be spectacularly bad at?", 4, 5, 3, 5, 5],
  ["audience-question", "Where did you go every summer as a child?", 5, 5, 4, 5, 5, "", "Play the place as it is now, not as it was."],
  ["audience-question", "What's a rule your family had?", 5, 5, 4, 5, 5, "p"],
  ["audience-question", "What's something you're avoiding this week?", 4, 5, 4, 5, 5],
  ["audience-question", "What job did you think you would end up doing?", 4, 5, 4, 5, 5, "a"],
  ["audience-question", "What's the last thing you argued about?", 4, 5, 5, 5, 5, "p"],
  ["audience-question", "What's in your kitchen drawer?", 5, 5, 3, 5, 5],
  ["audience-question", "Name a place you've driven past a hundred times and never stopped.", 5, 5, 3, 5, 5, "a"],
  ["audience-question", "What's a smell that takes you somewhere?", 5, 5, 4, 5, 5],
  ["audience-question", "What was your first job's uniform?", 5, 5, 3, 5, 5, "a"],
  ["audience-question", "What's in your bag right now?", 5, 5, 3, 5, 5],
  ["audience-question", "What did you have for breakfast?", 4, 5, 2, 5, 5],
  ["audience-question", "What's the last thing you lost?", 4, 5, 4, 5, 5],
  ["audience-question", "What's a place you've been that was too hot?", 5, 5, 3, 5, 5],
  ["audience-question", "What's something you're bad at that you keep doing anyway?", 4, 5, 4, 5, 5],
  ["audience-question", "What's the longest you've ever waited for something?", 4, 5, 4, 5, 5],
  ["audience-question", "What's a shop you miss?", 5, 5, 4, 5, 5],
  ["audience-question", "What's something you own two of by accident?", 5, 5, 3, 5, 5],
  ["audience-question", "What did you want to be when you were seven?", 4, 5, 4, 5, 5],
  ["audience-question", "What's a sound you can't stand?", 4, 5, 3, 5, 5],
  ["audience-question", "What's the last thing you fixed?", 4, 5, 3, 5, 5],
  ["audience-question", "What's a game you played as a child that had made-up rules?", 5, 5, 3, 5, 5],
  ["audience-question", "Where's the furthest you've walked in one go?", 4, 5, 3, 5, 5],
  ["audience-question", "What's something you've never told your neighbours?", 4, 5, 5, 5, 5, "a"],
  ["audience-question", "What's the last photo you took?", 4, 5, 3, 5, 5],
  ["audience-question", "What's a chore you secretly like?", 4, 5, 3, 5, 5],
  ["audience-question", "What's a word you always spell wrong?", 4, 5, 2, 5, 5],
  ["audience-question", "What's the worst present you've been grateful for?", 5, 5, 4, 5, 5],
  ["audience-question", "What did you get in trouble for at school?", 5, 5, 4, 5, 5],
  ["audience-question", "What's something in your house that doesn't work?", 5, 5, 3, 5, 5],
  ["audience-question", "What's a meal you can cook without looking anything up?", 4, 5, 3, 5, 5],
  ["audience-question", "Where were you the last time it rained hard?", 4, 5, 3, 5, 5],
  ["audience-question", "What's a thing you've saved for and never bought?", 4, 5, 4, 5, 5, "p"],
  ["audience-question", "What's the last text you sent?", 4, 5, 4, 5, 5],
  ["audience-question", "What's a hobby you gave up on?", 4, 5, 4, 5, 5],
  ["audience-question", "What did you collect as a kid?", 5, 5, 3, 5, 5],
  ["audience-question", "What's the last thing you said sorry for?", 4, 5, 5, 5, 5],
  ["audience-question", "What's a bus or train journey you know by heart?", 5, 5, 3, 5, 5],
  ["audience-question", "Name something you've borrowed and not given back.", 5, 5, 4, 5, 5],
  ["audience-question", "What's the last thing you broke?", 4, 5, 4, 5, 5],
  ["audience-question", "What's a place you go when you need to think?", 4, 5, 4, 5, 5],
  ["audience-question", "What's a skill you learned from a grandparent?", 5, 5, 4, 5, 5, "p"],
  ["audience-question", "What's the strangest thing in your fridge?", 5, 5, 2, 5, 5],
  ["audience-question", "What's the first thing you'd grab in a fire?", 4, 5, 4, 5, 5],
  ["audience-question", "What's the last thing you stood in line for?", 4, 5, 3, 5, 5],
  ["audience-question", "What's an object you've had longer than any friend?", 5, 5, 5, 5, 5, "", "Take the object literally and the friend loosely."],
  ["audience-question", "What's something you did this week that nobody noticed?", 4, 5, 5, 5, 5],
  ["audience-question", "What's the last thing you built or made?", 4, 5, 3, 5, 5],
  ["audience-question", "What time did you wake up today, and why?", 4, 5, 3, 5, 5],
  ["audience-question", "What's a shortcut you take that isn't shorter?", 5, 5, 3, 5, 5],
  ["audience-question", "What's the last thing you pretended to understand?", 4, 5, 4, 5, 5],
  ["audience-question", "What's in the back of your car?", 5, 5, 3, 5, 5, "a"],
  ["audience-question", "What did you last say to a stranger?", 4, 5, 4, 5, 5],
  ["audience-question", "What's a song you know all the words to and wish you didn't?", 5, 5, 3, 5, 5],

  // ── Shared tasks ─────────────────────────────────────────────────────────
  ["task", "Two people assembling something with no instructions", 4, 5, 2, 5, 5],
  ["task", "A person teaching another person something physical", 4, 5, 3, 5, 5],
  ["task", "Two people who agree about everything", 3, 5, 3, 5, 5, "x"],
  ["task", "A scene where nobody may ask a question", 2, 5, 2, 4, 5, "x"],
  ["task", "Two people waiting for the same appointment", 4, 5, 3, 5, 5, "x"],
  ["task", "One person arriving late to something small", 4, 5, 3, 5, 5, "x"],
  ["task", "Two people looking at the same object and seeing different things", 4, 5, 3, 5, 5],
  ["task", "A scene played entirely in one corner of the room", 3, 5, 2, 5, 5, "x"],
  ["task", "Two people who have to whisper", 4, 5, 3, 5, 5],
  ["task", "Someone showing another person around a place they love", 4, 5, 4, 5, 5, "x"],
  ["task", "Two people trying to move something heavy", 4, 5, 2, 5, 5, "d"],
  ["task", "Two people who have arrived on the wrong day", 4, 5, 3, 5, 5, "x"],
  ["task", "Someone returning something they broke", 4, 5, 4, 5, 5],
  ["task", "Two people sheltering from rain", 4, 5, 3, 5, 5, "x"],
  ["task", "A first day at a place everyone else already knows", 4, 5, 4, 5, 5, "x"],
  ["task", "Two people who have to be quiet for different reasons", 4, 5, 3, 5, 5],
  ["task", "Someone explaining a rule they do not understand themselves", 4, 5, 3, 5, 5],
  ["task", "Two people sharing the last of something", 4, 5, 3, 5, 5, "d"],
  ["task", "A person waiting for someone who is very late", 4, 5, 4, 5, 5],
  ["task", "Two people assembling a tent", 5, 5, 2, 5, 5, "d", "Actually put up the tent. The disagreement is a bonus."],
  ["task", "Someone giving a tour of a place they dislike", 4, 5, 3, 5, 5, "x"],
  ["task", "Two people who both think they are in charge", 3, 5, 4, 5, 5, "x"],
  ["task", "A person trying to leave politely", 3, 5, 4, 5, 5],
  ["task", "Two people looking for the same missing thing", 4, 5, 3, 5, 5, "d"],
  ["task", "Someone learning a skill from a person with no patience", 4, 5, 4, 5, 5, "", "Do the skill for real, slowly. Impatience needs something to be impatient about."],
  ["task", "Two people who are early and have nothing to do", 4, 5, 2, 5, 5, "x"],
  ["task", "A person returning to a place after a long time", 4, 5, 4, 5, 5, "x"],
  ["task", "Two people carrying something fragile", 4, 5, 3, 5, 5, "d"],
  ["task", "Someone practising something in private who is discovered", 4, 5, 4, 5, 5],
  ["task", "Two people who disagree about which way to go", 4, 5, 3, 5, 5],
  ["task", "Two colleagues who have to deliver the same news separately", 4, 4, 4, 4, 5, "ax"],
  ["task", "Two people handing over a job, one of them leaving", 4, 5, 4, 5, 5, "ax"],
  ["task", "Someone showing the new person where everything actually is", 4, 5, 3, 5, 5, "ax"],
  ["task", "Two people who have been in the same meeting and heard different things", 4, 5, 3, 5, 5, "ax"],
  ["task", "A person asking for help they do not want to need", 3, 5, 5, 4, 5],
  ["task", "Two people fixing something neither of them understands", 4, 5, 2, 5, 5],
  ["task", "Someone thanking a person who does not remember doing it", 4, 5, 4, 5, 5],
  ["task", "Two people waiting for a decision made elsewhere", 3, 5, 3, 4, 5, "a"],
  ["task", "A person explaining their work to somebody outside it", 3, 5, 3, 5, 5, "a"],
  ["task", "Two people who agree completely and have to decide anyway", 3, 5, 3, 5, 5, "x"],
  ["task", "Two people wrapping a present that is an awkward shape", 5, 5, 2, 5, 5, "d"],
  ["task", "Someone teaching a card game they half remember", 4, 5, 2, 5, 5],
  ["task", "Two people hanging a picture and disagreeing about straight", 5, 5, 3, 5, 5, "d"],
  ["task", "Two people folding a fitted sheet", 5, 4, 2, 5, 5, "d"],
  ["task", "Someone reading a map to a person who is driving", 4, 5, 3, 5, 5, "ax"],
  ["task", "Two people packing one bag for two", 4, 5, 3, 5, 5],
  ["task", "Someone untangling a set of lights while the other holds the ladder", 5, 5, 2, 5, 5],
  ["task", "Two people trying to remember a song", 4, 5, 2, 5, 5],
  ["task", "Two people setting a table for more guests than there are chairs", 5, 5, 3, 5, 5],
  ["task", "Someone learning to whistle from someone who can", 4, 5, 2, 5, 5],
  ["task", "Two people trying to get a cat into a basket", 5, 5, 3, 5, 5],
  ["task", "Two people writing a card together", 4, 5, 3, 5, 5],
  ["task", "Someone being taught to ride a bike as an adult", 4, 5, 4, 5, 5, "a"],
  ["task", "Two people putting up a shelf with one screw too few", 5, 5, 3, 5, 5],
  ["task", "Two people taking a group photo of people who will not stand still", 5, 5, 2, 5, 5, "g"],
  ["task", "Someone being shown how to use the coffee machine", 4, 5, 2, 5, 5],
  ["task", "Two people building a sandcastle in a hurry", 5, 5, 2, 5, 5, "x"],
  ["task", "Someone teaching a handshake", 4, 5, 3, 5, 5],
  ["task", "Two people trying to get a sofa through a door", 5, 5, 3, 5, 5],
  ["task", "Two people counting something that keeps moving", 4, 5, 2, 5, 5],
  ["task", "Someone rehearsing an apology with a friend", 4, 5, 4, 5, 5],
  ["task", "Two people sharing one umbrella", 4, 5, 3, 5, 5, "d"],
  ["task", "Two people trying to open a jar", 4, 5, 2, 5, 5, "d"],
  ["task", "Someone learning to tie a tie before a photograph", 5, 5, 3, 5, 5],
  ["task", "Two people decorating a cake against the clock", 5, 5, 2, 5, 5],
  ["task", "Someone giving directions to a place they have never been", 4, 5, 3, 5, 5],
  ["task", "Two people lifting a kayak onto a roof", 5, 5, 2, 5, 5, "x"],
  ["task", "Two people planting a tree that is bigger than they expected", 5, 5, 2, 5, 5, "x"],
  ["task", "Someone teaching a dance step they learned wrong", 4, 5, 3, 5, 5],
  ["task", "Two people deciding who sleeps where in a small tent", 4, 5, 3, 5, 5, "x"],
  ["task", "Two people checking every pocket for the key", 4, 5, 3, 5, 5],
  ["task", "Someone reading out the rules of a game as it is being played", 4, 5, 2, 5, 5],
  ["task", "Two people trying to leave one message on an answerphone together", 4, 5, 3, 5, 5],
  ["task", "Two people clearing snow off a car with the wrong tools", 5, 5, 2, 5, 5, "x"],
  ["task", "Someone being taught to swim by someone impatient", 4, 5, 3, 5, 5],
  ["task", "Two people fixing a flat at the roadside", 5, 5, 2, 5, 5, "x"],
  ["task", "Two people making a bed with the sheet the wrong way round", 5, 5, 2, 5, 5],
  ["task", "Someone signing for a parcel that is not for them", 4, 5, 3, 5, 5],
  ["task", "Two people carrying a ladder through a busy room", 5, 5, 2, 5, 5, "x"],
  ["task", "Two people looking at the same map and pointing in different directions", 4, 5, 3, 5, 5],
  ["task", "Someone painting a wall while the other says they have missed a bit", 5, 5, 3, 5, 5],
  ["task", "Two people on a walk, one of whom keeps stopping", 4, 5, 3, 5, 5, "x"],
  ["task", "Someone loading a dishwasher, watched by someone who does it differently", 5, 5, 3, 5, 5],
  ["task", "Two people trying to fit everything into the back of the car", 5, 5, 2, 5, 5, "x"],
  ["task", "Two people writing a sign for a lost pet", 5, 5, 4, 5, 5, "", "Argue about the wording. The pet is the thing you agree on."],
  ["task", "Someone practising a speech to a person who keeps correcting it", 4, 5, 3, 5, 5],
  ["task", "Two people playing a board game with pieces missing", 4, 5, 2, 5, 5],
  ["task", "Two people taking down a party tent in the wind", 5, 5, 2, 5, 5, "x"],
  // Added 2026-09-30 after reading the field (docs/improv-prompts-competitors.md):
  // an object and a job were the two kinds of start every other generator had
  // and this bank lacked. They belong inside the kinds that exist — a location
  // that names the object in it, a task that names the job — not as new cards.
  ["location", "A waiting room with one working vending machine", 5, 5, 3, 5, 5],
  ["location", "A garage with a car up on the ramp and nobody in it", 5, 5, 3, 5, 5],
  ["location", "A classroom with a broken projector and a full whiteboard", 5, 5, 2, 5, 5],
  ["location", "A kitchen with the smoke alarm going and the window painted shut", 5, 5, 3, 5, 5],
  ["location", "A church hall with one folding table left to put away", 5, 5, 2, 5, 5],
  ["location", "A hotel corridor with a room-service tray outside every door", 5, 5, 3, 5, 5],
  ["location", "A bus shelter with a timetable that is three years old", 5, 5, 2, 5, 5],
  ["location", "A landing with a suitcase that will not close", 5, 5, 3, 5, 5],
  ["location", "A shop doorway with a delivery nobody has signed for", 5, 5, 3, 5, 5],
  ["location", "A park bench with a bag of shopping left on it", 5, 5, 3, 5, 5],
  ["task", "Two movers and a piano on a landing", 5, 5, 3, 5, 5],
  ["task", "A locksmith opening a door while the owner explains that it is theirs", 5, 5, 3, 5, 5, "a"],
  ["task", "Two waiters resetting a table between sittings", 5, 5, 2, 5, 5],
  ["task", "Two groomers washing a dog that will not stay in the bath", 5, 5, 2, 5, 5],
  ["task", "An electrician explaining why it will cost more than they said", 4, 5, 4, 5, 5, "a"],
  ["task", "Two decorators wallpapering round a light switch", 5, 5, 2, 5, 5],
  ["task", "A learner reversing round a corner while the examiner writes", 5, 5, 4, 5, 5, "a"],
  ["task", "Two farmers getting a sheep back through the gap it came out of", 5, 5, 2, 5, 5],
  ["task", "A pharmacist explaining the label to someone in a hurry", 4, 5, 3, 5, 5, "a"],
  ["task", "Two stagehands striking a set in the dark", 5, 5, 2, 5, 5],
  ["task", "Someone delivering a parcel that does not fit through anything", 5, 5, 2, 5, 5],
  ["task", "Two lifeguards closing the pool while one swimmer keeps going", 5, 5, 3, 5, 5],
  // The twist the field sells as a button, as situations: what changes halfway
  // through, for a round where the leader calls the change.
  ["situation", "Halfway through, the third person turns out to have been listening", 4, 5, 5, 4, 5, "g"],
  ["situation", "Halfway through, one of you remembers where you have met before", 4, 5, 5, 5, 5],
  ["situation", "Halfway through, the phone rings and it is for the other one", 4, 5, 4, 5, 5],
  ["situation", "Halfway through, it starts to rain on both of you", 4, 5, 2, 5, 5],
  ["situation", "Halfway through, one of you finds the note", 4, 5, 5, 5, 5],
  ["situation", "Halfway through, the bus arrives and only one of you can get on", 5, 5, 4, 5, 5],
  ["situation", "Halfway through, someone you were talking about walks in", 4, 5, 5, 4, 5, "g"],
  ["situation", "Halfway through, one of you realises the other cannot hear a word", 4, 5, 4, 4, 5],
  ["situation", "Halfway through, the thing you were waiting for arrives and it is the wrong one", 4, 5, 4, 5, 5],
  ["situation", "Halfway through, the lights come back on", 4, 5, 3, 5, 5],
  ["relationship", "A crossing guard and the one kid who is always last across", 4, 4, 3, 5, 5, "x", "They both like the daily minute. Neither will say so."],
  ["relationship", "Two lab partners given one pair of goggles", 5, 4, 3, 5, 5],
  ["relationship", "A goalkeeper and the defender who let the striker through", 4, 4, 4, 5, 5, "x"],
  ["relationship", "Two people who both answered the same lost-cat poster", 5, 5, 3, 5, 5, "", "Neither has the cat. Find out what each of them wanted."],
  ["relationship", "Two people who have been given one map between them", 4, 5, 3, 5, 5],
  ["relationship", "A bus driver and the kid who rides to the end of the line every day", 5, 4, 3, 5, 5, "", "The driver has noticed. Play the day one of them finally says something."],
  ["relationship", "A lifeguard and the swimmer who asks about the rules every time", 4, 4, 2, 5, 5],
  ["relationship", "The two slowest runners in the race, at the back together", 5, 4, 3, 5, 5, "x"],
  ["relationship", "A school librarian and the student who reads only the last page", 5, 4, 2, 5, 5],
  ["relationship", "Two teammates who both think they are the captain", 4, 5, 4, 5, 5, "", "Neither wants the job for its own sake. Find out what each wants it for."],
  ["relationship", "A tour guide and the visitor who has been here before", 4, 5, 3, 5, 5],
  ["relationship", "Two people who both brought the same dish to the shared lunch", 5, 4, 2, 5, 5],
  ["relationship", "A skateboarder and the person whose fence they keep hitting", 5, 4, 3, 5, 5],
  ["relationship", "Two people who have to share one locker all year", 4, 5, 3, 5, 5],
  ["relationship", "A referee's assistant and the coach who will not sit down", 4, 4, 3, 4, 5, "x"],
  ["relationship", "A bike mechanic and the kid who fixed it with tape", 5, 4, 2, 5, 5],
  ["relationship", "Two campers who each thought the other had brought the matches", 5, 4, 3, 5, 5, "", "Nobody fetches matches. Play what it is like to be cold together."],
  ["relationship", "A ferry deckhand and the passenger who has never been on a boat", 4, 4, 2, 5, 5],
  ["relationship", "A student and the substitute teacher on the first day", 4, 5, 3, 5, 5, "x"],
  ["relationship", "Two people who were both sure the other one had the tickets", 4, 4, 4, 5, 5, "", "The tickets are gone. The scene is what they do with the evening instead."],
  ["relationship", "A coach and the player who scored the own goal", 4, 4, 4, 5, 5, "", "Play it kind. The comedy is in how hard both of them try not to mention it."],
  ["relationship", "Two people who taught the same dog different tricks", 5, 4, 3, 5, 5],
  ["relationship", "A piano tuner and the child who has been told not to touch anything", 5, 4, 2, 5, 5],
  ["relationship", "Two neighbours whose cats have swapped homes", 5, 4, 3, 5, 5],
  ["relationship", "The first person on the field and the one who forgot their shoes", 4, 4, 3, 5, 5, "x"],
  ["relationship", "A crossing guard and the cyclist who never stops in time", 4, 4, 3, 5, 5],
  ["relationship", "Two people who signed up for the wrong club and stayed", 4, 5, 3, 5, 5, "", "What they came for and what they found are different things. Play the second."],
  ["relationship", "Two people handing out leaflets for rival school council candidates", 4, 4, 3, 4, 5, "x"],
  ["relationship", "The newest member of the choir and the one who has been in it longest", 4, 4, 2, 5, 5],
  ["relationship", "Two people who have to take the class hamster home for the summer", 5, 4, 3, 5, 5],
  ["relationship", "A tennis coach and the player who returns every ball too hard", 4, 4, 3, 5, 5],
  ["relationship", "Two people chosen last for opposite teams", 4, 5, 3, 5, 5, "", "They have more in common than either side. Let them find it."],
  ["relationship", "A museum guard and the child who touched the exhibit", 5, 4, 3, 5, 5],
  ["relationship", "Two people on a rope swing that only holds one", 5, 3, 3, 4, 5, "x"],
  ["relationship", "A vet's receptionist and the kid who brought in a worm", 5, 4, 2, 5, 5],
  ["relationship", "The student who won the science fair and the one who built the same thing", 4, 4, 4, 5, 5],
  ["relationship", "A lighthouse keeper and the visitor who climbed all the way up to ask the way", 4, 4, 2, 5, 5],
  ["relationship", "Two people who each think they are the one being surprised", 4, 4, 3, 4, 5, "", "Neither can say it. Play the effort of keeping a secret you do not have."],
  ["relationship", "A scout leader and the one scout who has read the whole manual", 4, 4, 2, 5, 5],
  ["relationship", "A swimming teacher and the child who will not put their face in", 5, 4, 3, 5, 5],
  ["relationship", "Two people who both promised to look after the class plant", 4, 4, 3, 5, 5],
  ["relationship", "A photographer and the one person in the group who will not smile", 4, 4, 3, 5, 5],
  ["relationship", "The oldest and the youngest in a beginners' swimming class", 4, 4, 2, 5, 5],
  ["relationship", "The person who cleans the classroom and the student who leaves notes for them", 5, 4, 3, 5, 5, "", "Play the first time they meet in person."],
  ["audience-question", "What's the best thing you've ever found on the ground?", 4, 5, 3, 5, 5, "", "Take the finding, not the thing: who was there, and what they did next."],
  ["audience-question", "What did you build that fell down?", 4, 5, 3, 5, 5],
  ["audience-question", "What's something you've lent that came back different?", 4, 4, 3, 5, 5],
  ["audience-question", "Where's the one place in a school nobody goes?", 5, 5, 3, 5, 5, "", "Two people who both go there. Play the first time they meet in it."],
  ["audience-question", "What's a place you've been lost in?", 4, 5, 3, 5, 5],
  ["audience-question", "What's a rule you follow that nobody told you?", 4, 5, 3, 5, 5],
  ["audience-question", "What's the last thing you gave away?", 4, 4, 3, 5, 5],
  ["audience-question", "What do you always take with you and never use?", 4, 4, 2, 5, 5],
  ["audience-question", "What's the last thing you counted?", 4, 4, 2, 5, 5],
  ["audience-question", "What's a noise your house makes at night?", 5, 4, 2, 5, 5],
  ["audience-question", "What's something you did because someone dared you to?", 4, 5, 3, 5, 5],
  ["audience-question", "What's the last thing you waited in the rain for?", 5, 4, 3, 5, 5, "", "The waiting is the scene, not what they waited for."],
  ["audience-question", "What's the first thing you notice in a room?", 4, 5, 2, 5, 5],
  ["audience-question", "What's the last thing you did for the first time?", 4, 5, 3, 5, 5],
  ["audience-question", "What did you swap, and regret it?", 4, 4, 3, 5, 5],
  ["audience-question", "What's a name you've given to something that isn't a pet?", 5, 4, 2, 5, 5],
  ["audience-question", "What's the last thing you carried that was too heavy?", 5, 4, 3, 5, 5],
  ["audience-question", "What did you find in a pocket you'd forgotten about?", 5, 4, 2, 5, 5, "", "Play the moment before they remember what it was for."],
  ["audience-question", "What's a word you say too much?", 4, 4, 2, 5, 5],
  ["audience-question", "What's the last thing you watched twice?", 4, 4, 2, 5, 5],
  ["audience-question", "What's a path you take that isn't on any map?", 5, 4, 2, 5, 5],
  ["audience-question", "What's a thing you've never been able to open?", 5, 4, 3, 5, 5],
  ["audience-question", "Where do you go when it's raining and you have nowhere to be?", 5, 4, 2, 5, 5],
  ["audience-question", "What's the last thing you drew?", 4, 4, 2, 5, 5],
  ["audience-question", "What's something you know how to do that nobody taught you?", 4, 5, 3, 5, 5, "", "Play the person watching them do it."],
  ["audience-question", "What's a place that always smells the same?", 5, 4, 2, 5, 5],
  ["audience-question", "What's the last thing you said no to?", 4, 5, 3, 5, 5],
  ["audience-question", "What's a thing you keep in the wrong place on purpose?", 5, 4, 2, 5, 5],
  ["audience-question", "What's something you've been told you're too old for?", 4, 5, 3, 5, 5],
  ["audience-question", "What's the last thing you measured?", 4, 4, 2, 5, 5],
  ["audience-question", "What's the last thing you got wrong on purpose?", 4, 5, 3, 5, 5],
  ["audience-question", "What's the smallest thing you've ever been happy about?", 4, 5, 2, 5, 5, "", "Play it big. The small thing is the whole scene."],
  ["audience-question", "What's something you were sure you'd hate and didn't?", 4, 5, 3, 5, 5],
  ["audience-question", "What's a place you've been told to keep out of?", 5, 5, 3, 5, 5, "", "Somebody goes in anyway. Play the first minute."],
  ["audience-question", "What's the last thing you learned by accident?", 4, 5, 2, 5, 5],
  ["audience-question", "What do you do while you wait for the kettle?", 5, 4, 2, 5, 5],
  ["audience-question", "What's the last thing you put back on the shelf?", 4, 4, 2, 5, 5],
  ["audience-question", "What's a thing you can't do neatly?", 4, 4, 2, 5, 5],
  ["audience-question", "What's the last thing you got stuck in?", 5, 4, 3, 5, 5],
  ["audience-question", "What's the longest you've kept a secret?", 4, 5, 3, 5, 5, "", "The secret is never said. Play the two people keeping it from each other."],
  ["audience-question", "What's a thing you always volunteer for?", 4, 4, 2, 5, 5],
  ["audience-question", "What's the last thing you climbed?", 5, 4, 3, 5, 5],
];
