/**
 * Where each line of the classic can be.
 *
 * Reported on 2026-10-08, after the axes were made pure: "they still end up
 * being incohesive too often ... why would they be loading a dishwasher in a
 * school library". Three independent draws from three clean pools give
 * 433,650 triples and most of them cannot happen. Purity is a property of one
 * line; this is the thing no line can know on its own.
 *
 * The clash is almost always with the Where. In the reported draw the Who and
 * the What were fine together — neighbours loading a dishwasher is a scene —
 * and it was the school library that could hold neither. So the Where is the
 * anchor: it is the one line that is unambiguously a physical place, and the
 * other two are drawn to fit it.
 *
 * Every location names the kinds of place it is. A relationship or a task
 * names the kinds of place it can happen in, or `anywhere` when it travels —
 * "two people trying to open a jar" needs no particular room, and a good
 * half of the best prompts are like that, which is what keeps the
 * combinatorics up once the constraint is on.
 *
 * `anywhere` is a claim, not a default. A missing entry fails
 * prompt-cohesion.test.ts rather than passing as portable, because the last
 * bug in this subject was exactly that: `combinable` defaulted to true and a
 * batch of rows nobody had thought about joined the draw silently.
 */

/**
 * The kinds of place a scene can sit in. Coarse on purpose: a finer grid
 * would be more accurate per triple and would leave each location with too
 * few partners to feel like a generator.
 */
export const PROMPT_SETTINGS = [
  "home",
  "school",
  "work",
  "retail",
  "care",
  "transit",
  "leisure",
  "outdoors",
  "civic",
  "hospitality",
] as const;

export type PromptSetting = (typeof PROMPT_SETTINGS)[number];

/** Travels: plays in any of the settings above. */
export const ANYWHERE = "anywhere";

/**
 * Keyed by the prompt's own text, so an entry cannot drift onto the wrong row
 * and a reworded prompt shows up as a missing entry rather than a wrong one.
 */
export const PROMPT_SETTING_ROWS: Record<string, string> = {
  // ---- Locations: what kind of place this is. Never `anywhere`. ----
  "A laundromat at two in the morning": "retail",
  "The waiting area at a passport office": "civic",
  "A rented camper in the rain": "transit|outdoors",
  "A flea market, packing up": "retail|outdoors",
  "The waiting room of a fertility clinic": "care",
  "A hotel breakfast buffet": "hospitality",
  "An empty office on Christmas Eve": "work",
  "A cable car that has stopped": "transit|leisure",
  "The corner of the plant nursery nobody goes to": "retail|outdoors",
  "A funeral director's showroom": "civic|retail",
  "A laundromat that is also a post office": "retail|civic",
  "The car park after the wedding": "transit|hospitality",
  "A campsite where it will not stop raining": "outdoors",
  "Someone's childhood bedroom, unchanged": "home",
  "A ferry crossing in bad weather": "transit",
  "The lost property room at a station": "transit",
  "A shed at the bottom of a garden": "home|outdoors",
  "An airport gate after the last flight": "transit",
  "A lighthouse, being decommissioned": "work|outdoors",
  "A school corridor during an exam": "school",
  "The back row of a coach on a long trip": "transit",
  "A swimming pool changing room, after closing": "leisure",
  "A phone box that still works": "outdoors",
  "The last checkout open at a supermarket": "retail",
  "A community hall being set up for something": "civic",
  "The top deck of a bus in the rain": "transit",
  "A stairwell in a multi-storey car park": "transit",
  "The kitchen at a wedding reception": "hospitality|work",
  "A community garden plot in November": "outdoors",
  "A dentist's waiting room with the radio on": "care",
  "An elevator that has stopped between floors": "work|transit",
  "A bookshop five minutes before closing": "retail",
  "The changing rooms at a clothes shop": "retail",
  "A pier in the off-season": "outdoors|leisure",
  "A canal path at dusk": "outdoors",
  "The waiting area at a tyre garage": "retail",
  "The staff room during a fire drill": "work",
  "A museum gift shop": "leisure|retail",
  "A rooftop with washing lines": "home|outdoors",
  "A tent in a back garden": "home|outdoors",
  "The kiosk at an ice rink": "leisure|retail",
  "A night bus, the last one": "transit",
  "A hospital corridor at visiting time": "care",
  "A vet's waiting room": "care",
  "A car wash, from inside the car": "transit|retail",
  "A school library in the summer holidays": "school",
  "The changing hut on a beach": "outdoors|leisure",
  "A highway service station at three in the morning": "transit|retail",
  "The self-checkout that keeps needing assistance": "retail",
  "A greenhouse in a heatwave": "home|outdoors",
  "The lobby of a hotel that has lost the booking": "hospitality",
  "The back room of a second-hand shop, sorting donations": "retail|work",
  "A bike shed in the rain": "school|outdoors",
  "A fire station open day": "civic",
  "A hospice garden": "care|outdoors",
  "A campground office": "outdoors|work",
  "A train yard at the end of the line": "transit|work",
  "A radio station at four in the morning": "work",
  "A barber's, the seat by the window": "retail",
  "The stockroom of a shoe shop": "retail|work",
  "An aquarium after the school parties have left": "leisure",
  "The wait for a photo booth": "retail|leisure",
  "A recording booth that smells of the last person": "work",
  "A model village": "leisure|outdoors",
  "A fish market at dawn": "retail|work",
  "A waiting room with one working vending machine": "care|civic",
  "A garage with a car up on the ramp and nobody in it": "retail|work",
  "A classroom with a broken projector and a full whiteboard": "school",
  "A kitchen with the smoke alarm going and the window painted shut": "home",
  "A church hall with one folding table left to put away": "civic",
  "A hotel corridor with a room-service tray outside every door": "hospitality",
  "A bus shelter with a timetable that is three years old": "transit|outdoors",
  "A landing with a suitcase that will not close": "home",
  "A shop doorway with a delivery nobody has signed for": "retail",
  "A park bench with a bag of shopping left on it": "outdoors",

  // ---- Tasks: where the doing can happen. ----
  "Two people assembling something with no instructions": ANYWHERE,
  "A person teaching another person something physical": ANYWHERE,
  "Two people looking at the same object and seeing different things": ANYWHERE,
  "Two people who have to whisper": ANYWHERE,
  "Two people trying to move something heavy": ANYWHERE,
  "Someone returning something they broke": ANYWHERE,
  "Two people who have to be quiet for different reasons": ANYWHERE,
  "Someone explaining a rule they do not understand themselves": ANYWHERE,
  "Two people sharing the last of something": ANYWHERE,
  "A person waiting for someone who is very late": ANYWHERE,
  "Two people assembling a tent": "outdoors|home",
  "A person trying to leave politely": ANYWHERE,
  "Two people looking for the same missing thing": ANYWHERE,
  "Someone learning a skill from a person with no patience": ANYWHERE,
  "Two people carrying something fragile": ANYWHERE,
  "Someone practising something in private who is discovered": ANYWHERE,
  "Two people who disagree about which way to go": ANYWHERE,
  "A person asking for help they do not want to need": ANYWHERE,
  "Two people fixing something neither of them understands": ANYWHERE,
  "Someone thanking a person who does not remember doing it": ANYWHERE,
  "Two people waiting for a decision made elsewhere": ANYWHERE,
  "A person explaining their work to somebody outside it": ANYWHERE,
  "Two people wrapping a present that is an awkward shape": "home|retail|work",
  "Someone teaching a card game they half remember": ANYWHERE,
  "Two people hanging a picture and disagreeing about straight": "home|work|civic",
  "Two people folding a fitted sheet": "home|hospitality|care",
  "Two people packing one bag for two": "home|transit|hospitality",
  "Someone untangling a set of lights while the other holds the ladder": "home|work|civic|retail",
  "Two people trying to remember a song": ANYWHERE,
  "Two people setting a table for more guests than there are chairs": "home|hospitality|civic",
  "Someone learning to whistle from someone who can": ANYWHERE,
  "Two people trying to get a cat into a basket": "home|care",
  "Two people writing a card together": ANYWHERE,
  "Someone being taught to ride a bike as an adult": "outdoors",
  "Two people putting up a shelf with one screw too few": "home|work|retail",
  "Two people taking a group photo of people who will not stand still": ANYWHERE,
  "Someone being shown how to use the coffee machine": "work|hospitality|home",
  "Someone teaching a handshake": ANYWHERE,
  "Two people trying to get a sofa through a door": "home",
  "Two people counting something that keeps moving": ANYWHERE,
  "Two people sharing one umbrella": "outdoors",
  "Two people trying to open a jar": "home|hospitality|work",
  "Someone learning to tie a tie before a photograph": "home|school|hospitality",
  "Two people decorating a cake against the clock": "home|hospitality",
  "Someone giving directions to a place they have never been": ANYWHERE,
  "Someone teaching a dance step they learned wrong": ANYWHERE,
  "Two people checking every pocket for the key": ANYWHERE,
  "Someone reading out the rules of a game as it is being played": ANYWHERE,
  "Two people trying to leave one message on an answerphone together": "home|work",
  "Someone being taught to swim by someone impatient": "leisure",
  "Two people making a bed with the sheet the wrong way round": "home|hospitality|care",
  "Someone signing for a parcel that is not for them": "home|work|retail",
  "Two people looking at the same map and pointing in different directions": ANYWHERE,
  "Someone painting a wall while the other says they have missed a bit": "home|work|school|civic",
  "Someone loading a dishwasher, watched by someone who does it differently": "home|hospitality",
  "Two people writing a sign for a lost pet": "home|outdoors|retail",
  "Someone practising a speech to a person who keeps correcting it": ANYWHERE,
  "Two people playing a board game with pieces missing": "home|school|care|civic|hospitality",
  "Someone delivering a parcel that does not fit through anything": "home|work|retail",

  // ---- Relationships: where this pair plausibly meets. ----
  "A driving instructor and a student who is forty": "transit|outdoors",
  "Best friends, one of whom just got the job the other applied for": ANYWHERE,
  "Two people who used to be in a band together": ANYWHERE,
  "A doctor and a patient who went to school together": "care",
  "Neighbours who share a fence and disagree about it": "home|outdoors",
  "A parent helping an adult child move out again": "home",
  "Two people who matched online and have now met": ANYWHERE,
  "A manager and the person they are about to promote": "work",
  "Old friends, one of whom has become religious": ANYWHERE,
  "A landlord and a tenant who is three weeks late": "home",
  "A grandparent teaching a grandchild to drive": "transit|outdoors",
  "Someone and their ex's new partner": ANYWHERE,
  "Two people who were briefly famous together": ANYWHERE,
  "A coach and the player they are dropping": "leisure|school",
  "Roommates dividing what they bought together": "home",
  "A translator and the person they are translating for": ANYWHERE,
  "Two people who have been on one date before": ANYWHERE,
  "A parent and the teacher who called them in": "school",
  "Siblings deciding who takes the dog": ANYWHERE,
  "A priest and someone who has stopped coming": "civic",
  "Two people who used to work night shifts together": ANYWHERE,
  "A tailor and a customer for a suit they will wear once": "retail",
  "Someone and the person who trained them, years later": ANYWHERE,
  "Two people who survived the same accident": ANYWHERE,
  "A new kid and the one told to show them round": "school|work",
  "Two people paired for a project who have never spoken": "school|work",
  "A lifeguard and a swimmer who will not get out": "leisure",
  "A librarian and someone returning a book ten years late": "civic|school",
  "Two pen pals meeting for the first time": ANYWHERE,
  "A shop assistant and a customer returning a gift without a receipt": "retail",
  "A referee and the player they have just sent off": "leisure|school",
  "A dog walker and the owner of the dog": "outdoors|home",
  "A mentor and the mentee who has overtaken them": "work",
  "Two people who share a birthday and a name": ANYWHERE,
  "A piano teacher and a pupil who has not practised": "home|school",
  "Two neighbours who only ever meet on recycling day": "home|outdoors",
  "Two old friends who have not spoken since the argument": ANYWHERE,
  "Two people who were both promised the window seat": "transit",
  "A ghostwriter and the person whose name will be on the book": ANYWHERE,
  "A retiring postal worker and someone on the last house of the round": "home|outdoors",
  "A hairdresser and a regular who wants something different this time": "retail",
  "Someone and the person who found their wallet": ANYWHERE,
  "Two people who are both sure the seat is theirs": "transit|leisure",
  "A plumber and a customer who has already tried to fix it": "home",
  "A student and the teacher who wrote their reference": "school",
  "Two cousins who only meet at weddings": "hospitality|civic",
  "A shopkeeper and a child with the wrong change": "retail",
  "A guide and the one tourist who keeps wandering off": "leisure|outdoors",
  "The retiring head of a school and the student they expelled": "school",
  "A florist and someone ordering flowers for an apology": "retail",
  "Two people who have just swapped shifts and regret it": "work",
  "A trainee and the customer who knows more than they do": "retail|work",
  "Two people who have each been told the other is in charge": "work",
  "The person who won the raffle and the person who ran it": "civic",
  "Someone and the friend who cut their hair for the first time": "home",
  "Two housemates, one of whom has adopted a cat without asking": "home",
  "A ticket inspector and someone with the wrong ticket": "transit",
  "Someone and the neighbour who has been keeping their parcel": "home",
  "A choir director and the singer who is always flat": "civic|school",
  "Two people who both got engaged the same weekend": ANYWHERE,
  "A gardener and the person whose garden it is": "home|outdoors",
  "Two people who both volunteered for the job nobody wanted": ANYWHERE,
  "Someone renting a room and the owner of the house, who can smell the cooking": "home",
  "An apprentice and the master who is about to retire": "work",
  "Two lab partners given one pair of goggles": "school",
  "Two people who both answered the same lost-cat poster": ANYWHERE,
  "Two people who have been given one map between them": "outdoors|leisure|transit",
  "A bus driver and the kid who rides to the end of the line every day": "transit",
  "A lifeguard and the swimmer who asks about the rules every time": "leisure",
  "A school librarian and the student who reads only the last page": "school",
  "Two teammates who both think they are the captain": "leisure|school",
  "A tour guide and the visitor who has been here before": "leisure|outdoors",
  "Two people who both brought the same dish to the shared lunch": "work|civic|home",
  "A skateboarder and the person whose fence they keep hitting": "outdoors|home",
  "Two people who have to share one locker all year": "school|leisure",
  "A bike mechanic and the kid who fixed it with tape": "retail|outdoors",
  "Two campers who each thought the other had brought the matches": "outdoors",
  "Two people who were both sure the other one had the tickets": "transit|leisure",
  "A coach and the player who scored the own goal": "leisure|school",
  "Two people who taught the same dog different tricks": "home|outdoors",
  "A piano tuner and the child who has been told not to touch anything": "home|school",
  "Two neighbours whose cats have swapped homes": "home",
  "A crossing guard and the cyclist who never stops in time": "outdoors|school",
  "Two people who signed up for the wrong club and stayed": "school|civic|leisure",
  "The newest member of the choir and the one who has been in it longest": "civic|school",
  "Two people who have to take the class hamster home for the summer": "school|home",
  "A tennis coach and the player who returns every ball too hard": "leisure",
  "Two people chosen last for opposite teams": "school|leisure",
  "A museum guard and the child who touched the exhibit": "leisure",
  "A vet's receptionist and the kid who brought in a worm": "care",
  "The student who won the science fair and the one who built the same thing": "school",
  "A lighthouse keeper and the visitor who climbed all the way up to ask the way": "work|outdoors",
  "Two people who each think they are the one being surprised": ANYWHERE,
  "A scout leader and the one scout who has read the whole manual": "outdoors|civic",
  "A swimming teacher and the child who will not put their face in": "leisure",
  "Two people who both promised to look after the class plant": "school",
  "A photographer and the one person in the group who will not smile": ANYWHERE,
  "The person who cleans the classroom and the student who leaves notes for them": "school",
};
