import type { TwentyOneQuestion } from "./twenty-one-questions-bank";

/**
 * The 181 questions of /21-questions-game: the 21 the article runs in order,
 * and the 160 under its eight headings, one row per bullet.
 *
 * Generated from the article and held against it by
 * twenty-one-questions-bank.test.ts: every row here is a bullet there and every
 * bullet there is a row here, and the ordered 21 are its numbered list, so the
 * tool can never ask a question the page does not print.
 *
 * Do not hand-edit: change the article and regenerate, or the guard fails.
 */
export const TWENTY_ONE_IN_ORDER: readonly string[] = [
  "What was the first thing you did this morning?",
  "What do you cook when you cannot be bothered?",
  "What are you good at that never comes up?",
  "What did you want to be at ten years old?",
  "What is the best thing you have spent money on this year?",
  "What has caught your attention lately?",
  "What was your street like when you were small?",
  "What did you nearly do instead of what you do now?",
  "What standard do you hold yourself to that nobody checks?",
  "What is something you have changed your mind about?",
  "What are you better at than you were five years ago?",
  "What is currently taking more out of you than you admit?",
  "What do you do when things get difficult?",
  "What is something you are slightly embarrassed to enjoy?",
  "What is a decision you still think about?",
  "What assumption do people make about you that is wrong?",
  "What is something you have never been very good at accepting?",
  "What is on your list that keeps getting moved?",
  "What has been the hardest year, and what got you through it?",
  "What do you want that you have not said out loud?",
  "What have I not asked that I should have?",
];

export const TWENTY_ONE_QUESTION_ROWS: readonly TwentyOneQuestion[] = [
  { id: "good-01", category: "good", text: "What is the last thing that changed your plans?" },
  { id: "good-02", category: "good", text: "What reliably lifts a bad day?" },
  { id: "good-03", category: "good", text: "What would you do with a completely free week?" },
  {
    id: "good-04",
    category: "good",
    text: "What is something you own that you would not replace?",
  },
  { id: "good-05", category: "good", text: "What is a habit you are glad you have?" },
  { id: "good-06", category: "good", text: "What do you spend more on than you would admit?" },
  { id: "good-07", category: "good", text: "What is the best advice you have ignored?" },
  { id: "good-08", category: "good", text: "What is something you find easy that others do not?" },
  {
    id: "good-09",
    category: "good",
    text: "What did you believe as a child that took years to shake?",
  },
  { id: "good-10", category: "good", text: "What is a place you think about often?" },
  {
    id: "good-11",
    category: "good",
    text: "What would your fifteen-year-old self be pleased about?",
  },
  { id: "good-12", category: "good", text: "What did you give up that turned out to be easy?" },
  { id: "good-13", category: "good", text: "What is the last thing you learned properly?" },
  { id: "good-14", category: "good", text: "What do you do that is entirely for yourself?" },
  { id: "good-15", category: "good", text: "What is a compliment you have never forgotten?" },
  {
    id: "good-16",
    category: "good",
    text: "What is the most useful thing anybody has ever said to you?",
  },
  { id: "good-17", category: "good", text: "What are you hoping this year contains?" },
  {
    id: "good-18",
    category: "good",
    text: "What is something you were talked into and are glad about?",
  },
  { id: "good-19", category: "good", text: "What do you notice first about people?" },
  {
    id: "good-20",
    category: "good",
    text: "What is a thing you have kept for no practical reason?",
  },
  { id: "good-21", category: "good", text: "What is something you would happily do every day?" },
  { id: "good-22", category: "good", text: "What has become noticeably easier for you lately?" },
  {
    id: "good-23",
    category: "good",
    text: "What is the strangest job you would genuinely consider?",
  },
  { id: "good-24", category: "good", text: "What would you like to have more time for?" },
  { id: "good-25", category: "good", text: "What is a story about you that gets told often?" },
  {
    id: "good-26",
    category: "good",
    text: "What is something you find genuinely difficult to talk about?",
  },
  { id: "good-27", category: "good", text: "What is the kindest thing you have seen somebody do?" },
  { id: "good-28", category: "good", text: "What are you proud of that nobody knows about?" },
  { id: "good-29", category: "good", text: "What is a thing you always say yes to?" },
  { id: "good-30", category: "good", text: "What would you never do again?" },
  {
    id: "fun-01",
    category: "fun",
    text: "What is the worst film you have watched all the way through?",
  },
  { id: "fun-02", category: "fun", text: "What is your most-used app, honestly?" },
  { id: "fun-03", category: "fun", text: "What is the best meal you have had this year?" },
  { id: "fun-04", category: "fun", text: "What would you never get rid of?" },
  { id: "fun-05", category: "fun", text: "What is an unpopular opinion you will defend?" },
  { id: "fun-06", category: "fun", text: "What is your go-to karaoke song, hypothetically?" },
  { id: "fun-07", category: "fun", text: "What is the last photo in your camera roll?" },
  {
    id: "fun-08",
    category: "fun",
    text: "What is something you are unreasonably competitive about?",
  },
  { id: "fun-09", category: "fun", text: "What is your most useless talent?" },
  { id: "fun-10", category: "fun", text: "What food could you not live without?" },
  { id: "fun-11", category: "fun", text: "What would you miss if you moved away tomorrow?" },
  { id: "fun-12", category: "fun", text: "What is your worst habit?" },
  { id: "fun-13", category: "fun", text: "What would you do first if you woke up rich?" },
  { id: "fun-14", category: "fun", text: "What did you do for money before this?" },
  { id: "fun-15", category: "fun", text: "What is the strangest thing you have eaten?" },
  { id: "fun-16", category: "fun", text: "What is a trend you never understood?" },
  { id: "fun-17", category: "fun", text: "What is your idea of a perfect Sunday?" },
  { id: "fun-18", category: "fun", text: "What would you name a boat?" },
  { id: "fun-19", category: "fun", text: "What is the best gift you have received?" },
  { id: "fun-20", category: "fun", text: "What is something everybody likes and you do not?" },
  { id: "fun-21", category: "fun", text: "What is the last thing you laughed at properly?" },
  { id: "fun-22", category: "fun", text: "What sound instantly puts you somewhere else?" },
  { id: "fun-23", category: "fun", text: "What would you put on a billboard?" },
  { id: "fun-24", category: "fun", text: "What is your favourite thing to do alone?" },
  { id: "deep-01", category: "deep", text: "What are you most afraid of losing?" },
  { id: "deep-02", category: "deep", text: "When did you last feel genuinely proud of yourself?" },
  { id: "deep-03", category: "deep", text: "What do you think you are still working out?" },
  { id: "deep-04", category: "deep", text: "What would you tell yourself at twenty?" },
  { id: "deep-05", category: "deep", text: "What has been the loneliest period of your life?" },
  { id: "deep-06", category: "deep", text: "What do you need that you find hard to ask for?" },
  {
    id: "deep-07",
    category: "deep",
    text: "What do you think people misunderstand about your family?",
  },
  {
    id: "deep-08",
    category: "deep",
    text: "What is something you have forgiven that you did not expect to?",
  },
  { id: "deep-09", category: "deep", text: "What did your upbringing get right?" },
  { id: "deep-10", category: "deep", text: "What do you think you are running from?" },
  { id: "deep-11", category: "deep", text: "When have you surprised yourself?" },
  { id: "deep-12", category: "deep", text: "What do you want to be true of you in ten years?" },
  { id: "deep-13", category: "deep", text: "What is the thing you are proudest of surviving?" },
  { id: "deep-14", category: "deep", text: "What do you wish somebody had told you earlier?" },
  { id: "deep-15", category: "deep", text: "What do you find hardest to say to people you love?" },
  { id: "deep-16", category: "deep", text: "What is a regret you have made peace with?" },
  {
    id: "deep-17",
    category: "deep",
    text: "What would you do differently if nobody was watching?",
  },
  { id: "deep-18", category: "deep", text: "What has changed most about what you want?" },
  { id: "deep-19", category: "deep", text: "What do you think you owe the people around you?" },
  { id: "deep-20", category: "deep", text: "What is the question you avoid?" },
  { id: "couples-01", category: "couples", text: "What was the moment you knew?" },
  { id: "couples-02", category: "couples", text: "What do you think I do not realise about you?" },
  { id: "couples-03", category: "couples", text: "What has been your favourite year of us?" },
  {
    id: "couples-04",
    category: "couples",
    text: "What do you need more of that you have not asked for?",
  },
  { id: "couples-05", category: "couples", text: "What do you think we are best at together?" },
  {
    id: "couples-06",
    category: "couples",
    text: "What would you want us to do more of next year?",
  },
  {
    id: "couples-07",
    category: "couples",
    text: "What is something you have never told me about your childhood?",
  },
  { id: "couples-08", category: "couples", text: "What do you think I worry about?" },
  { id: "couples-09", category: "couples", text: "When do you feel most yourself with me?" },
  {
    id: "couples-10",
    category: "couples",
    text: "What is a small thing I do that you would miss?",
  },
  { id: "couples-11", category: "couples", text: "What do you think we should talk about more?" },
  {
    id: "couples-12",
    category: "couples",
    text: "What is something you have changed your mind about since we met?",
  },
  {
    id: "couples-13",
    category: "couples",
    text: "What would you want me to do if you were struggling?",
  },
  {
    id: "couples-14",
    category: "couples",
    text: "What do you want us to still be doing in twenty years?",
  },
  { id: "couples-15", category: "couples", text: "What is something you find hard to say to me?" },
  {
    id: "couples-16",
    category: "couples",
    text: "What do we rely on each other for without ever saying?",
  },
  { id: "met-01", category: "met", text: "What brought you here?" },
  { id: "met-02", category: "met", text: "What does an ordinary week look like for you?" },
  { id: "met-03", category: "met", text: "What is occupying most of your time?" },
  { id: "met-04", category: "met", text: "What did you do before this?" },
  { id: "met-05", category: "met", text: "Where is home, originally?" },
  { id: "met-06", category: "met", text: "What do you do when you are not working?" },
  { id: "met-07", category: "met", text: "What have you been enjoying lately?" },
  {
    id: "met-08",
    category: "met",
    text: "What is the best thing you have read or watched recently?",
  },
  { id: "met-09", category: "met", text: "What is the next good thing in your diary?" },
  { id: "met-10", category: "met", text: "What did you study, and do you use it?" },
  { id: "met-11", category: "met", text: "What is something you have always wanted to try?" },
  { id: "met-12", category: "met", text: "What would you do if work stopped mattering tomorrow?" },
  { id: "met-13", category: "met", text: "Where would you go tomorrow if travel were free?" },
  { id: "met-14", category: "met", text: "How did you come to be part of this group?" },
  { id: "met-15", category: "met", text: "What are you better at than you expected to be?" },
  { id: "met-16", category: "met", text: "What is something you are curious about at the moment?" },
  { id: "like-01", category: "like", text: "Why did this seem like a good idea at the time?" },
  { id: "like-02", category: "like", text: "What is the first thing you noticed about me?" },
  { id: "like-03", category: "like", text: "What is your idea of a good evening?" },
  {
    id: "like-04",
    category: "like",
    text: "What are you like when you are completely comfortable?",
  },
  {
    id: "like-05",
    category: "like",
    text: "What do you find attractive that has nothing to do with looks?",
  },
  {
    id: "like-06",
    category: "like",
    text: "What is something you would want somebody to know early?",
  },
  { id: "like-07", category: "like", text: "What does a good week do for your mood?" },
  { id: "like-08", category: "like", text: "What is the nicest thing somebody has done for you?" },
  {
    id: "like-09",
    category: "like",
    text: "What would you want to do together that neither of us has done?",
  },
  { id: "like-10", category: "like", text: "What makes you laugh that you cannot explain?" },
  { id: "like-11", category: "like", text: "What are you hopeless at?" },
  { id: "like-12", category: "like", text: "What is missing from your life at the moment?" },
  { id: "like-13", category: "like", text: "What is something you would like to be asked?" },
  { id: "like-14", category: "like", text: "What would surprise me about you?" },
  { id: "family-01", category: "family", text: "What were your parents like at my age?" },
  { id: "family-02", category: "family", text: "What is a family story you are not sure is true?" },
  { id: "family-03", category: "family", text: "What did our kitchen sound like on a Sunday?" },
  {
    id: "family-04",
    category: "family",
    text: "Who in the family are you most like, and do you mind?",
  },
  {
    id: "family-05",
    category: "family",
    text: "What rule in this house was never actually enforced?",
  },
  {
    id: "family-06",
    category: "family",
    text: "What is something you wish you had asked your grandparents?",
  },
  {
    id: "family-07",
    category: "family",
    text: "What did you think of me when I was a teenager, honestly?",
  },
  { id: "family-08", category: "family", text: "What tradition do you actually enjoy?" },
  {
    id: "family-09",
    category: "family",
    text: "What is the hardest thing you have not told me about?",
  },
  { id: "family-10", category: "family", text: "What do you think this family is good at?" },
  { id: "family-11", category: "family", text: "What did you give up that nobody noticed?" },
  { id: "family-12", category: "family", text: "What was the best year for us, in your view?" },
  { id: "family-13", category: "family", text: "What do you wish we did differently?" },
  {
    id: "family-14",
    category: "family",
    text: "What is something about your childhood I would find surprising?",
  },
  { id: "family-15", category: "family", text: "What did you worry about that turned out fine?" },
  { id: "family-16", category: "family", text: "What would you want said at your eightieth?" },
  {
    id: "family-17",
    category: "family",
    text: "What is a decision of yours that changed everything for us?",
  },
  { id: "family-18", category: "family", text: "What do you think I inherited from you?" },
  {
    id: "family-19",
    category: "family",
    text: "What is something you have forgiven and never mentioned?",
  },
  {
    id: "family-20",
    category: "family",
    text: "What do you hope we still do together in ten years?",
  },
  {
    id: "thinks-01",
    category: "thinks",
    text: "How do you decide when you have enough information?",
  },
  { id: "thinks-02", category: "thinks", text: "What changes your mind, in practice?" },
  { id: "thinks-03", category: "thinks", text: "Do you trust your gut or check it?" },
  {
    id: "thinks-04",
    category: "thinks",
    text: "What do you do when two people you respect disagree?",
  },
  {
    id: "thinks-05",
    category: "thinks",
    text: "How do you tell whether you are being stubborn or principled?",
  },
  { id: "thinks-06", category: "thinks", text: "What kind of problem do you enjoy?" },
  { id: "thinks-07", category: "thinks", text: "Do you think out loud or after the fact?" },
  { id: "thinks-08", category: "thinks", text: "What makes you stop trusting somebody?" },
  { id: "thinks-09", category: "thinks", text: "How do you know when something is finished?" },
  { id: "thinks-10", category: "thinks", text: "What do you do with advice you did not ask for?" },
  { id: "thinks-11", category: "thinks", text: "Are you better under pressure or with time?" },
  { id: "thinks-12", category: "thinks", text: "What do you do when you are wrong in public?" },
  { id: "thinks-13", category: "thinks", text: "How do you choose what to ignore?" },
  {
    id: "thinks-14",
    category: "thinks",
    text: "What is a belief you hold that you cannot fully justify?",
  },
  { id: "thinks-15", category: "thinks", text: "Do you plan the route or start walking?" },
  {
    id: "thinks-16",
    category: "thinks",
    text: "What convinces you \u2014 evidence, or somebody you trust?",
  },
  {
    id: "thinks-17",
    category: "thinks",
    text: "How do you handle a decision with no good option?",
  },
  { id: "thinks-18", category: "thinks", text: "What do you notice that you wish you did not?" },
  { id: "thinks-19", category: "thinks", text: "Do you prefer to be told or to work it out?" },
  {
    id: "thinks-20",
    category: "thinks",
    text: "What is the last thing you deliberately changed about how you think?",
  },
];
