/**
 * Where each city sits on the map, in the units of US_MAP_VIEWBOX.
 *
 * Generated by scripts/build-us-map.mjs from data/map/city-points.json
 * (US Census 2023 Gazetteer) and us-atlas's 1:10m states, projected with
 * geoAlbersUsa. Do not edit: run the script.
 *
 * Each row is [slug, x, y, markerX, markerY]. The first pair is where the
 * city is; the second is where its target had to move to so that no two
 * targets overlap at the map's narrowest render (see MIN_SEPARATION in the
 * script). Where the two differ the map draws a hairline between them, so a
 * moved marker still points at its city. The tightest pair is
 * tampa/orlando at 36 units; the longest move is
 * oakland at 19.6.
 */
export const US_MAP_VIEWBOX = { width: 975, height: 610 } as const;

/** [slug, x, y, markerX, markerY] */
export type UsMapRow = readonly [string, number, number, number, number];

// prettier-ignore
export const US_MAP_ROWS: readonly UsMapRow[] = [
  ["new-york", 892.4, 215.5, 894.8, 207.6],
  ["los-angeles", 135.7, 356.3, 119.1, 361.6],
  ["chicago", 667.8, 225.6, 668.9, 229.8],
  ["houston", 545.5, 496.1, 545.5, 496.1],
  ["phoenix", 245.1, 388.7, 230.5, 386.7],
  ["philadelphia", 876.4, 233.9, 878, 239.4],
  ["san-antonio", 486, 502.5, 479.4, 508.8],
  ["san-diego", 152.2, 387.2, 151.8, 392.3],
  ["dallas", 520, 430.3, 533.4, 419],
  ["san-jose", 96, 271.5, 84.3, 286.6],
  ["austin", 501, 484.6, 506.1, 484.6],
  ["jacksonville", 802.2, 463.8, 802.2, 463.8],
  ["fort-worth", 509.3, 430.4, 496.6, 418.2],
  ["columbus", 748.7, 257.5, 752.8, 253.9],
  ["charlotte", 800.6, 355.9, 800.6, 355.9],
  ["indianapolis", 697.2, 268.3, 694.5, 267.2],
  ["san-francisco", 88.9, 258.5, 77.6, 250.4],
  ["seattle", 149, 51.5, 149, 51.5],
  ["denver", 386.7, 270.2, 386.6, 262.1],
  ["washington", 850.8, 264.2, 862.8, 272],
  ["nashville", 694.3, 348.3, 694.3, 348.3],
  ["oklahoma-city", 507.3, 371.4, 505.4, 372.3],
  ["el-paso", 342, 440.5, 342, 440.5],
  ["boston", 929.3, 168.2, 930.8, 155.8],
  ["portland", 132.2, 93.8, 132.2, 93.8],
  ["las-vegas", 200.6, 320.8, 200.6, 320.8],
  ["detroit", 739.6, 205.5, 736.3, 203.6],
  ["memphis", 640.5, 376.1, 640.5, 376.1],
  ["louisville", 709.3, 302.7, 705, 307.8],
  ["baltimore", 855.7, 254.3, 842.1, 242.5],
  ["milwaukee", 661, 199.2, 659.9, 194.9],
  ["albuquerque", 346, 369, 346, 369],
  ["tucson", 261.9, 423.1, 261.4, 427.2],
  ["fresno", 126.7, 291.4, 132.1, 292.3],
  ["sacramento", 109.1, 246.1, 107, 227.2],
  ["kansas-city", 558.1, 291, 558.1, 291],
  ["mesa", 251.1, 393.6, 266.2, 391.5],
  ["atlanta", 741.7, 396.4, 741.7, 396.4],
  ["omaha", 533, 244.1, 533, 244.1],
  ["colorado-springs", 386.8, 290, 386.9, 298.1],
  ["raleigh", 836.3, 335.9, 836, 337.1],
  ["long-beach", 138.7, 362.4, 155.2, 356.4],
  ["virginia-beach", 876.8, 306.6, 878.5, 306.8],
  ["miami", 845.6, 557.3, 845.6, 557.3],
  ["oakland", 92, 259.6, 111.4, 262.9],
  ["minneapolis", 576, 162.4, 576, 162.4],
  ["tulsa", 535.6, 357.1, 537.5, 356.1],
  ["bakersfield", 131.8, 325.1, 132.7, 328.3],
  ["wichita", 510.9, 322.5, 510.9, 322.5],
  ["arlington", 513.4, 432.3, 514.2, 449.5],
  ["new-orleans", 648.2, 486.7, 648.2, 486.7],
  ["cleveland", 765.1, 221.9, 767.7, 221.2],
  ["tampa", 794.4, 517.2, 789.8, 519.9],
  ["pittsburgh", 796.2, 240, 797.8, 241],
  ["st-louis", 630.9, 298.9, 630.9, 298.9],
  ["cincinnati", 726, 279.1, 728.1, 280.2],
  ["orlando", 816.3, 504.2, 820.8, 501.5],
  ["salt-lake-city", 274.4, 232.9, 274.4, 232.9],
  ["richmond", 849.1, 295.4, 842.4, 301.7],
  ["providence", 926, 180.8, 927.1, 191.7],
];

export interface UsMapPlace {
  slug: string;
  /** Where the city is. */
  x: number;
  y: number;
  /** Where its target sits, moved only as far as crowding demanded. */
  markerX: number;
  markerY: number;
  /** Whether the target had to move, so the map knows to draw the hairline. */
  moved: boolean;
}

export const US_MAP_PLACES: readonly UsMapPlace[] = US_MAP_ROWS.map(
  ([slug, x, y, markerX, markerY]) => ({
    slug,
    x,
    y,
    markerX,
    markerY,
    moved: Math.hypot(markerX - x, markerY - y) > 1,
  }),
);

export const US_MAP_PLACE_BY_SLUG: ReadonlyMap<string, UsMapPlace> = new Map(
  US_MAP_PLACES.map((place) => [place.slug, place]),
);
