import type { WouldYouRatherPair } from "./would-you-rather-bank";

/**
 * The 164 pairs of /would-you-rather-questions, one row per bullet, split into
 * the two options the reader picks between.
 *
 * Generated from the article and held against it by
 * would-you-rather-bank.test.ts: every row here is a bullet there and every
 * bullet there is a row here, so the tool can never offer a pair the page does
 * not list. The split is the article's own sentence shape — the options are
 * separated by ", or " — and the one pair written without the comma ("Live
 * without hope or without fear?") splits on " or " instead.
 *
 * Do not hand-edit: change the article and regenerate, or the guard fails.
 */
export const WOULD_YOU_RATHER_ROWS: readonly WouldYouRatherPair[] = [
  {
    id: "good-01",
    category: "good",
    left: "Have every conversation recorded",
    right: "have no memory of any of them",
  },
  {
    id: "good-02",
    category: "good",
    left: "Be able to undo one decision a year",
    right: "see the outcome of one before you make it",
  },
  {
    id: "good-03",
    category: "good",
    left: "Lose the ability to lie",
    right: "lose the ability to keep a secret",
  },
  {
    id: "good-04",
    category: "good",
    left: "Have a job you love that nobody respects",
    right: "one you tolerate that everyone admires",
  },
  {
    id: "good-05",
    category: "good",
    left: "Always have to say what you are thinking",
    right: "never be able to say it",
  },
  {
    id: "good-06",
    category: "good",
    left: "Be able to talk to animals",
    right: "fluently read any language",
  },
  {
    id: "good-07",
    category: "good",
    left: "Have your best friend read your search history",
    right: "your parents read your messages",
  },
  { id: "good-08", category: "good", left: "Never be lonely again", right: "never be bored again" },
  {
    id: "good-09",
    category: "good",
    left: "Be able to fall asleep instantly",
    right: "wake up perfectly rested after four hours",
  },
  {
    id: "good-10",
    category: "good",
    left: "Live somewhere beautiful and far from everyone",
    right: "somewhere ugly and near them",
  },
  {
    id: "good-11",
    category: "good",
    left: "Get every joke you tell to land",
    right: "every question you ask to be answered honestly",
  },
  {
    id: "good-12",
    category: "good",
    left: "Have unlimited books but no music",
    right: "unlimited music but no books",
  },
  {
    id: "good-13",
    category: "good",
    left: "Know exactly how others see you",
    right: "never wonder about it again",
  },
  {
    id: "good-14",
    category: "good",
    left: "Be given the answer to any question once a year",
    right: "a small nudge every day",
  },
  {
    id: "good-15",
    category: "good",
    left: "Have to move house every year",
    right: "never be able to move again",
  },
  {
    id: "good-16",
    category: "good",
    left: "Be slightly underestimated forever",
    right: "slightly overestimated forever",
  },
  { id: "good-17", category: "good", left: "Have a perfect memory for faces", right: "for names" },
  {
    id: "good-18",
    category: "good",
    left: "Only ever travel somewhere you have been",
    right: "only somewhere you have not",
  },
  {
    id: "good-19",
    category: "good",
    left: "Be able to work anywhere",
    right: "never have to work past two o'clock",
  },
  {
    id: "good-20",
    category: "good",
    left: "Have your worst photo on a billboard",
    right: "your worst message read aloud",
  },
  {
    id: "good-21",
    category: "good",
    left: "Never feel cold again",
    right: "never feel tired again",
  },
  {
    id: "good-22",
    category: "good",
    left: "Be the funniest person in the room",
    right: "the one everyone trusts",
  },
  {
    id: "good-23",
    category: "good",
    left: "Have one close friend who knows everything",
    right: "ten who know some of it",
  },
  { id: "good-24", category: "good", left: "Choose your neighbours", right: "choose your commute" },
  {
    id: "adults-01",
    category: "adults",
    left: "Take a 30% pay cut for a four-day week",
    right: "a 30% rise for a six-day one",
  },
  {
    id: "adults-02",
    category: "adults",
    left: "Have complete control over your calendar",
    right: "over what you work on",
  },
  {
    id: "adults-03",
    category: "adults",
    left: "Retire at fifty with just enough",
    right: "at seventy with far more",
  },
  {
    id: "adults-04",
    category: "adults",
    left: "Have a manager who is kind and useless",
    right: "difficult and excellent",
  },
  {
    id: "adults-05",
    category: "adults",
    left: "Know exactly what your colleagues earn",
    right: "that none of them know what you earn",
  },
  {
    id: "adults-06",
    category: "adults",
    left: "Own a home you cannot leave",
    right: "rent anywhere forever",
  },
  {
    id: "adults-07",
    category: "adults",
    left: "Have one long career",
    right: "four completely unrelated ones",
  },
  {
    id: "adults-08",
    category: "adults",
    left: "Be respected in your field and unknown outside it",
    right: "the reverse",
  },
  {
    id: "adults-09",
    category: "adults",
    left: "Have every Friday off",
    right: "leave at three every day",
  },
  {
    id: "adults-10",
    category: "adults",
    left: "Get an hour of genuine focus a day",
    right: "four hours of interrupted work",
  },
  {
    id: "adults-11",
    category: "adults",
    left: "Find out you were wrong publicly and early",
    right: "right privately and too late",
  },
  {
    id: "adults-12",
    category: "adults",
    left: "Have all your debts cleared",
    right: "never worry about money again but keep them",
  },
  {
    id: "adults-13",
    category: "adults",
    left: "Be told the truth by everyone at work",
    right: "be well liked by all of them",
  },
  {
    id: "adults-14",
    category: "adults",
    left: "Live in the city you love with the job you tolerate",
    right: "the reverse",
  },
  {
    id: "adults-15",
    category: "adults",
    left: "Never attend another meeting",
    right: "never write another email",
  },
  {
    id: "adults-16",
    category: "adults",
    left: "Have your work matter to five people enormously",
    right: "five thousand slightly",
  },
  {
    id: "adults-17",
    category: "adults",
    left: "Take a year off now",
    right: "three months every five years",
  },
  {
    id: "adults-18",
    category: "adults",
    left: "Know when you are being lied to at work",
    right: "never be lied to but never know why",
  },
  { id: "hard-01", category: "hard", left: "Save one person you love", right: "five strangers" },
  {
    id: "hard-02",
    category: "hard",
    left: "Know the date of your death",
    right: "the manner of it",
  },
  {
    id: "hard-03",
    category: "hard",
    left: "Have everyone believe a lie that helps you",
    right: "a truth that harms you",
  },
  {
    id: "hard-04",
    category: "hard",
    left: "Lose every photograph you have",
    right: "every message you have ever sent",
  },
  {
    id: "hard-05",
    category: "hard",
    left: "Be able to prevent one disaster",
    right: "predict all of them and prevent none",
  },
  {
    id: "hard-06",
    category: "hard",
    left: "Live one more year knowing it",
    right: "twenty not knowing when",
  },
  {
    id: "hard-07",
    category: "hard",
    left: "Have your child be happy and ordinary",
    right: "brilliant and troubled",
  },
  { id: "hard-08", category: "hard", left: "Be forgotten entirely", right: "remembered wrongly" },
  {
    id: "hard-09",
    category: "hard",
    left: "Take the credit you did not earn",
    right: "lose the credit you did",
  },
  { id: "hard-10", category: "hard", left: "Have the power to end one war", right: "one illness" },
  {
    id: "hard-11",
    category: "hard",
    left: "Give up your closest friendship",
    right: "your career",
  },
  { id: "hard-12", category: "hard", left: "Be able to feel no grief", right: "no joy" },
  {
    id: "hard-13",
    category: "hard",
    left: "Never be betrayed",
    right: "never be tempted to betray",
  },
  {
    id: "hard-14",
    category: "hard",
    left: "Know a terrible truth about somebody you love",
    right: "have them know one about you",
  },
  {
    id: "hard-15",
    category: "hard",
    left: "Live in a fair world where you are worse off",
    right: "an unfair one where you are better off",
  },
  {
    id: "hard-16",
    category: "hard",
    left: "Have your worst act judged in public",
    right: "your best act go permanently unnoticed",
  },
  { id: "hard-17", category: "hard", left: "Be free and alone", right: "bound and among people" },
  {
    id: "hard-18",
    category: "hard",
    left: "Watch somebody make a mistake you could prevent by breaking a promise",
    right: "keep it",
  },
  {
    id: "deep-01",
    category: "deep",
    left: "Understand yourself completely",
    right: "be completely understood by one other person",
  },
  {
    id: "deep-02",
    category: "deep",
    left: "Have a life that feels good",
    right: "one that looks good in retrospect",
  },
  {
    id: "deep-03",
    category: "deep",
    left: "Be certain of something false",
    right: "unsure of something true",
  },
  {
    id: "deep-04",
    category: "deep",
    left: "Know why things happened to you",
    right: "that they will not happen again",
  },
  {
    id: "deep-05",
    category: "deep",
    left: "Be loved for who you are",
    right: "admired for what you did",
  },
  { id: "deep-06", category: "deep", left: "Have more time", right: "less need for it" },
  {
    id: "deep-07",
    category: "deep",
    left: "Be at peace with your regrets",
    right: "have fewer of them",
  },
  {
    id: "deep-08",
    category: "deep",
    left: "Know the person you would have been",
    right: "never wonder",
  },
  { id: "deep-09", category: "deep", left: "Be the one who leaves", right: "the one who is left" },
  {
    id: "deep-10",
    category: "deep",
    left: "Have your questions answered",
    right: "better questions",
  },
  { id: "deep-11", category: "deep", left: "Feel everything more intensely", right: "less" },
  {
    id: "deep-12",
    category: "deep",
    left: "Be remembered by many for one thing",
    right: "by one person for everything",
  },
  { id: "deep-13", category: "deep", left: "Live without hope", right: "without fear" },
  {
    id: "deep-14",
    category: "deep",
    left: "Be the reason somebody changed",
    right: "never know that you were",
  },
  {
    id: "deep-15",
    category: "deep",
    left: "Have made peace with your childhood",
    right: "with your future",
  },
  {
    id: "deep-16",
    category: "deep",
    left: "Know what you are for",
    right: "be free of the question",
  },
  { id: "fun-01", category: "fun", left: "Have a personal chef", right: "a personal driver" },
  { id: "fun-02", category: "fun", left: "Be able to teleport home", right: "anywhere but home" },
  {
    id: "fun-03",
    category: "fun",
    left: "Always have perfect weather",
    right: "never queue again",
  },
  {
    id: "fun-04",
    category: "fun",
    left: "Have every song you hear be one you like",
    right: "every film be one you have not seen",
  },
  {
    id: "fun-05",
    category: "fun",
    left: "Have unlimited free books",
    right: "unlimited free coffee",
  },
  { id: "fun-06", category: "fun", left: "Be able to speak to babies", right: "to plants" },
  {
    id: "fun-07",
    category: "fun",
    left: "Never have to charge anything again",
    right: "never have to clean anything again",
  },
  {
    id: "fun-08",
    category: "fun",
    left: "Have a house with an extra room",
    right: "a garden twice the size",
  },
  {
    id: "fun-09",
    category: "fun",
    left: "Be able to eat anything with no consequences",
    right: "sleep any amount and feel great",
  },
  {
    id: "fun-10",
    category: "fun",
    left: "Always get the window seat",
    right: "always get an upgrade to the next class",
  },
  {
    id: "fun-11",
    category: "fun",
    left: "Have every parcel arrive early",
    right: "every meeting end early",
  },
  {
    id: "fun-12",
    category: "fun",
    left: "Be able to change one thing about your commute",
    right: "one thing about your kitchen",
  },
  {
    id: "fun-13",
    category: "fun",
    left: "Have your favourite meal cooked perfectly by somebody else",
    right: "cook it perfectly yourself",
  },
  {
    id: "fun-14",
    category: "fun",
    left: "Get one extra hour in the morning",
    right: "one extra hour at night",
  },
  {
    id: "fun-15",
    category: "fun",
    left: "Have a shed at the bottom of the garden",
    right: "a balcony at the top of the house",
  },
  {
    id: "fun-16",
    category: "fun",
    left: "Always know the fastest route",
    right: "always find a parking space",
  },
  { id: "fun-17", category: "fun", left: "Be able to skip any queue", right: "mute any noise" },
  {
    id: "fun-18",
    category: "fun",
    left: "Have a permanent good hair day",
    right: "permanently comfortable shoes",
  },
  {
    id: "fun-19",
    category: "fun",
    left: "Never have a flat battery",
    right: "never have a slow connection",
  },
  {
    id: "fun-20",
    category: "fun",
    left: "Have somebody else do your admin",
    right: "your laundry",
  },
  {
    id: "couples-01",
    category: "couples",
    left: "Have a week apart every month",
    right: "never spend a night apart",
  },
  {
    id: "couples-02",
    category: "couples",
    left: "Know every thought the other has",
    right: "be certain they never lie to you",
  },
  {
    id: "couples-03",
    category: "couples",
    left: "Move somewhere neither of us knows",
    right: "stay near family forever",
  },
  {
    id: "couples-04",
    category: "couples",
    left: "Have more time together and less money",
    right: "the reverse",
  },
  {
    id: "couples-05",
    category: "couples",
    left: "Argue often and resolve it fast",
    right: "rarely and take days",
  },
  {
    id: "couples-06",
    category: "couples",
    left: "Be told the difficult thing immediately",
    right: "when the other has worked out how to say it",
  },
  {
    id: "couples-07",
    category: "couples",
    left: "Have completely separate friends",
    right: "entirely shared ones",
  },
  {
    id: "couples-08",
    category: "couples",
    left: "Take one long holiday a year",
    right: "a weekend away every month",
  },
  {
    id: "couples-09",
    category: "couples",
    left: "Both work from home",
    right: "never overlap in the house",
  },
  {
    id: "couples-10",
    category: "couples",
    left: "Have the same taste in everything",
    right: "none of it",
  },
  {
    id: "couples-11",
    category: "couples",
    left: "Be able to relive one day together",
    right: "see one day ten years ahead",
  },
  {
    id: "couples-12",
    category: "couples",
    left: "Split every task exactly",
    right: "each own half of them entirely",
  },
  {
    id: "couples-13",
    category: "couples",
    left: "Have a partner who is always honest",
    right: "always kind",
  },
  {
    id: "couples-14",
    category: "couples",
    left: "Keep one thing private forever",
    right: "have nothing private at all",
  },
  {
    id: "couples-15",
    category: "couples",
    left: "Have your relationship understood by everyone",
    right: "by nobody but you two",
  },
  {
    id: "couples-16",
    category: "couples",
    left: "Be the one who plans",
    right: "the one who is surprised",
  },
  {
    id: "couples-17",
    category: "couples",
    left: "Have a quiet life together",
    right: "an eventful one",
  },
  {
    id: "couples-18",
    category: "couples",
    left: "Fix a recurring argument permanently",
    right: "add one brilliant new shared thing",
  },
  {
    id: "couples-19",
    category: "couples",
    left: "Know how it ends",
    right: "never think about it",
  },
  {
    id: "couples-20",
    category: "couples",
    left: "Be each other's first call",
    right: "each other's last word on everything",
  },
  {
    id: "crazy-01",
    category: "crazy",
    left: "Have your shadow move independently",
    right: "your reflection lag behind",
  },
  {
    id: "crazy-02",
    category: "crazy",
    left: "Be permanently three inches taller",
    right: "three years younger",
  },
  {
    id: "crazy-03",
    category: "crazy",
    left: "Have everything you say appear as subtitles",
    right: "everything you think appear as weather above you",
  },
  { id: "crazy-04", category: "crazy", left: "Sweat maple syrup", right: "sneeze glitter" },
  {
    id: "crazy-05",
    category: "crazy",
    left: "Have to announce yourself in every room",
    right: "have a theme tune play instead",
  },
  { id: "crazy-06", category: "crazy", left: "Be unable to whisper", right: "unable to shout" },
  { id: "crazy-07", category: "crazy", left: "Have one enormous hand", right: "two tiny ones" },
  {
    id: "crazy-08",
    category: "crazy",
    left: "Live your life in fast forward",
    right: "with a two-second delay",
  },
  {
    id: "crazy-09",
    category: "crazy",
    left: "Have to hop everywhere indoors",
    right: "crawl everywhere outdoors",
  },
  { id: "crazy-10", category: "crazy", left: "Taste colour", right: "hear temperature" },
  {
    id: "crazy-11",
    category: "crazy",
    left: "Have a tail you cannot control",
    right: "ears that move when you lie",
  },
  {
    id: "crazy-12",
    category: "crazy",
    left: "Be followed everywhere by a small orchestra",
    right: "by a documentary crew",
  },
  {
    id: "crazy-13",
    category: "crazy",
    left: "Have all your clothes be one size too big",
    right: "one size too small",
  },
  {
    id: "crazy-14",
    category: "crazy",
    left: "Only walk backwards",
    right: "only speak in the past tense",
  },
  {
    id: "crazy-15",
    category: "crazy",
    left: "Have your bed always slightly damp",
    right: "your house always slightly too bright",
  },
  {
    id: "crazy-16",
    category: "crazy",
    left: "Have to eat everything with a teaspoon",
    right: "drink everything through a straw",
  },
  {
    id: "crazy-17",
    category: "crazy",
    left: "Be able to pause any conversation for ten seconds",
    right: "replay any ten seconds of one",
  },
  {
    id: "crazy-18",
    category: "crazy",
    left: "Have every mirror show you five minutes ago",
    right: "five minutes ahead",
  },
  {
    id: "crazy-19",
    category: "crazy",
    left: "Grow a new tooth every year",
    right: "lose one every decade",
  },
  {
    id: "crazy-20",
    category: "crazy",
    left: "Have to knock before entering any room including your own",
    right: "say goodbye to every room you leave",
  },
  {
    id: "crazy-21",
    category: "crazy",
    left: "Be permanently mildly itchy",
    right: "permanently mildly cold",
  },
  {
    id: "crazy-22",
    category: "crazy",
    left: "Have every drink be slightly too hot",
    right: "every seat be slightly too low",
  },
  {
    id: "crazy-23",
    category: "crazy",
    left: "Only ever travel by boat",
    right: "never leave the ground again",
  },
  {
    id: "crazy-24",
    category: "crazy",
    left: "Have your memory of yesterday",
    right: "your plan for tomorrow, be wrong every time",
  },
  { id: "kids-01", category: "kids", left: "Be able to fly", right: "breathe underwater" },
  {
    id: "kids-02",
    category: "kids",
    left: "Have a pet dragon the size of a cat",
    right: "a cat the size of a dragon",
  },
  {
    id: "kids-03",
    category: "kids",
    left: "Never have to sleep",
    right: "never have to go to school",
  },
  {
    id: "kids-04",
    category: "kids",
    left: "Eat only your favourite food forever",
    right: "never eat it again but eat anything else",
  },
  {
    id: "kids-05",
    category: "kids",
    left: "Be invisible for a day",
    right: "be able to talk to animals for a day",
  },
  { id: "kids-06", category: "kids", left: "Live in a treehouse", right: "in a boat" },
  {
    id: "kids-07",
    category: "kids",
    left: "Have a robot that does your chores",
    right: "one that does your homework",
  },
  {
    id: "kids-08",
    category: "kids",
    left: "Be the fastest runner in the world",
    right: "the best at drawing",
  },
  {
    id: "kids-09",
    category: "kids",
    left: "Always have wet socks",
    right: "always have sand in your shoes",
  },
  { id: "kids-10", category: "kids", left: "Have hands for feet", right: "feet for hands" },
  {
    id: "kids-11",
    category: "kids",
    left: "Be able to freeze time for ten minutes",
    right: "rewind it by ten minutes",
  },
  {
    id: "kids-12",
    category: "kids",
    left: "Have a slide instead of stairs",
    right: "a trampoline instead of a bed",
  },
  {
    id: "kids-13",
    category: "kids",
    left: "Always be a little bit too hot",
    right: "a little bit too cold",
  },
  {
    id: "kids-14",
    category: "kids",
    left: "Have every day be your birthday",
    right: "every day be a snow day",
  },
  {
    id: "kids-15",
    category: "kids",
    left: "Only be able to whisper",
    right: "only be able to shout",
  },
  {
    id: "kids-16",
    category: "kids",
    left: "Be able to shrink to the size of a mouse",
    right: "grow to the size of a house",
  },
  {
    id: "kids-17",
    category: "kids",
    left: "Have a swimming pool full of jelly",
    right: "a bathtub full of chocolate",
  },
  {
    id: "kids-18",
    category: "kids",
    left: "Never lose a game",
    right: "always be the one who makes everybody laugh",
  },
  {
    id: "kids-19",
    category: "kids",
    left: "Be able to breathe fire",
    right: "make ice with your hands",
  },
  {
    id: "kids-20",
    category: "kids",
    left: "Have a magic pencil that draws real things",
    right: "a book that reads itself aloud",
  },
  {
    id: "kids-21",
    category: "kids",
    left: "Live where it is always summer",
    right: "always autumn",
  },
  {
    id: "kids-22",
    category: "kids",
    left: "Have wheels instead of feet",
    right: "wings instead of arms",
  },
  {
    id: "kids-23",
    category: "kids",
    left: "Be able to understand any animal",
    right: "be understood by all of them",
  },
  {
    id: "kids-24",
    category: "kids",
    left: "Have a house made of sweets you cannot eat",
    right: "vegetables you can",
  },
];
